// ============================================================
// Enhanced Service Data: business & daily domains
// "무엇이든 심사받으세요" MVP
// ============================================================

export const DATA_BD = {
  business: {
    personal: [],
    sole: [
      {
        name: "소상공인 지원금 자격",
        desc: "소상공인 정부 지원금 수급 자격 진단",
        diff: "간편",
        time: 3,
        docs: ["사업자등록증", "매출 내역"],
        fields: [
          { key: "revenue", label: "연 매출 (만원)", type: "number", placeholder: "예: 30000" },
          { key: "employees", label: "상시 근로자 수", type: "number", placeholder: "예: 4" },
          { key: "industry", label: "업종", type: "select", options: ["음식점업", "소매업", "서비스업", "제조업", "숙박업", "기타"] },
          { key: "yearsInBusiness", label: "사업 기간 (년)", type: "number", placeholder: "예: 2" },
          { key: "region", label: "사업장 소재지", type: "select", options: ["서울", "경기", "인천", "부산", "대구", "대전", "광주", "세종", "강원", "기타"] },
          { key: "previousSupport", label: "기존 정부지원금 수혜 여부", type: "select", options: ["없음", "1회", "2회", "3회 이상"] },
        ],
        considerations: [
          "소상공인 기본법상 업종별 상시근로자 수 기준 (제조업 10인 미만, 기타 5인 미만)",
          "최근 3년간 연 매출 규모에 따른 소기업·소상공인 분류",
          "동일 사업자의 중복수혜 제한 여부 확인",
          "업종별 제외 업종 해당 여부 (유흥업, 부동산업 등)",
        ],
        references: [
          { name: "소상공인진흥공단", url: "https://www.semas.or.kr" },
          { name: "중소벤처기업부 지원사업 통합공고", url: "https://www.mss.go.kr" },
          { name: "창업진흥원 K-Startup", url: "https://www.k-startup.go.kr" },
        ],
      },
      {
        name: "창업자금 적격",
        desc: "정부 창업지원자금 적격 여부 진단",
        diff: "표준",
        time: 7,
        docs: ["사업계획서", "창업자 경력", "업종 정보"],
        fields: [
          { key: "founderAge", label: "대표자 나이", type: "number", placeholder: "예: 35" },
          { key: "businessAge", label: "창업 후 경과 기간 (개월)", type: "number", placeholder: "예: 12" },
          { key: "industry", label: "업종 분류", type: "select", options: ["제조업", "지식서비스업", "ICT", "문화콘텐츠", "사회적기업", "일반서비스업", "기타"] },
          { key: "fundingAmount", label: "희망 자금 규모 (만원)", type: "number", placeholder: "예: 10000" },
          { key: "teamSize", label: "창업팀 인원", type: "number", placeholder: "예: 3" },
          { key: "priorExperience", label: "관련 업종 경력 (년)", type: "number", placeholder: "예: 5" },
          { key: "hasBusinessPlan", label: "사업계획서 보유", type: "select", options: ["상세 작성 완료", "초안 작성", "미작성"] },
        ],
        considerations: [
          "예비창업자 또는 창업 3년 이내(초기창업) / 7년 이내(도약기) 기준 충족 여부",
          "업력별 지원 프로그램 구분 (예비창업패키지, 초기창업패키지, 창업도약패키지 등)",
          "대표자의 재창업 여부 및 신용상태",
          "기술 기반 창업 우대 적용 가능 여부",
          "사업계획서 완성도 및 시장성·실현가능성 평가",
        ],
        references: [
          { name: "창업진흥원 K-Startup", url: "https://www.k-startup.go.kr" },
          { name: "중소벤처기업부", url: "https://www.mss.go.kr" },
          { name: "소상공인진흥공단", url: "https://www.semas.or.kr" },
        ],
      },
      {
        name: "기술보증 적격",
        desc: "기술보증기금 보증 적격 여부 진단",
        diff: "정밀",
        time: 10,
        docs: ["기술 내역", "사업계획서", "재무제표"],
        fields: [
          { key: "techType", label: "보유 기술 유형", type: "select", options: ["특허", "실용신안", "소프트웨어", "노하우", "디자인", "기타"] },
          { key: "techCount", label: "보유 기술(특허) 건수", type: "number", placeholder: "예: 3" },
          { key: "revenue", label: "최근 연 매출 (만원)", type: "number", placeholder: "예: 50000" },
          { key: "operatingProfit", label: "영업이익 (만원)", type: "number", placeholder: "예: 5000" },
          { key: "rdRatio", label: "매출 대비 R&D 비율 (%)", type: "number", placeholder: "예: 10" },
          { key: "guaranteeAmount", label: "희망 보증 금액 (만원)", type: "number", placeholder: "예: 30000" },
          { key: "existingGuarantee", label: "기존 보증 잔액 (만원)", type: "number", placeholder: "예: 0" },
          { key: "creditGrade", label: "기업 신용등급", type: "select", options: ["AAA~AA", "A", "BBB", "BB", "B", "CCC 이하"] },
        ],
        considerations: [
          "기술성 평가: 기술의 완성도, 독창성, 시장성 종합 판단",
          "기술사업계획서(TBP) 평가등급이 일정 수준 이상이어야 보증 가능",
          "기존 보증 잔액 및 한도 초과 여부",
          "부실 우려 기업, 휴폐업 기업 등 보증 제한 대상 해당 여부",
          "기술 인력 보유 현황 및 R&D 투자 비중",
        ],
        references: [
          { name: "기술보증기금", url: "https://www.kibo.or.kr" },
          { name: "중소벤처기업부", url: "https://www.mss.go.kr" },
          { name: "창업진흥원", url: "https://www.k-startup.go.kr" },
        ],
      },
      {
        name: "벤처기업 인증 가능성",
        desc: "벤처기업 확인 인증 가능성 진단",
        diff: "정밀",
        time: 10,
        docs: ["기술력 증빙", "재무제표", "사업계획서"],
        fields: [
          { key: "certType", label: "희망 인증 유형", type: "select", options: ["벤처투자유형", "연구개발유형", "기술평가보증유형", "기술평가대출유형", "예비벤처"] },
          { key: "vcInvestment", label: "벤처투자 유치 금액 (만원)", type: "number", placeholder: "예: 50000" },
          { key: "rdExpense", label: "연간 R&D 비용 (만원)", type: "number", placeholder: "예: 10000" },
          { key: "revenue", label: "연 매출 (만원)", type: "number", placeholder: "예: 100000" },
          { key: "techAssets", label: "보유 지재권 수", type: "number", placeholder: "예: 5" },
          { key: "companyAge", label: "설립 후 경과 기간 (년)", type: "number", placeholder: "예: 3" },
          { key: "rdPersonnel", label: "R&D 인력 비율 (%)", type: "number", placeholder: "예: 30" },
        ],
        considerations: [
          "벤처투자유형: 투자금액이 자본금의 10% 이상인지 확인",
          "연구개발유형: R&D 비용이 매출의 5%(창업 3년 이내는 매출 무관) 이상인지 확인",
          "기술평가유형: 기보/중진공 기술성 평가 등급 충족 여부",
          "업력별 인증 유형 적합도 및 갱신 요건",
        ],
        references: [
          { name: "중소벤처기업부", url: "https://www.mss.go.kr" },
          { name: "한국벤처투자", url: "https://www.kvic.or.kr" },
          { name: "기술보증기금", url: "https://www.kibo.or.kr" },
          { name: "벤처확인종합관리시스템", url: "https://www.venturein.or.kr" },
        ],
      },
      {
        name: "1인 법인 전환 적격",
        desc: "1인 법인 전환 적격 및 절세 효과 분석",
        diff: "표준",
        time: 7,
        docs: ["매출 내역", "소득 내역", "사업 구조"],
        fields: [
          { key: "annualIncome", label: "연간 사업소득 (만원)", type: "number", placeholder: "예: 10000" },
          { key: "revenue", label: "연 매출 (만원)", type: "number", placeholder: "예: 50000" },
          { key: "expenses", label: "연간 필요경비 (만원)", type: "number", placeholder: "예: 30000" },
          { key: "industry", label: "업종", type: "select", options: ["제조업", "도소매업", "서비스업", "IT업", "프리랜서", "기타"] },
          { key: "hasEmployees", label: "직원 유무", type: "select", options: ["없음 (1인)", "1~2명", "3~5명", "5명 이상"] },
          { key: "taxBurden", label: "현재 종합소득세 부담 (만원)", type: "number", placeholder: "예: 2000" },
        ],
        considerations: [
          "종합소득세율(6~45%) vs 법인세율(9~24%) 비교를 통한 절세 효과",
          "법인 전환 시 4대보험, 법인 유지비용 등 추가 비용 발생 고려",
          "부가세 환급, 퇴직금 적립 등 법인 전환의 추가 이점",
          "업종별 법인 전환 시 인허가 재취득 필요 여부",
          "법인 전환 방식 (현물출자, 사업양수도, 포괄양수도) 선택",
        ],
        references: [
          { name: "중소벤처기업부", url: "https://www.mss.go.kr" },
          { name: "소상공인진흥공단", url: "https://www.semas.or.kr" },
          { name: "창업진흥원", url: "https://www.k-startup.go.kr" },
        ],
      },
    ],
    corp: [
      {
        name: "정부 R&D 과제 적격",
        desc: "정부 R&D 지원 과제 참여 적격 진단",
        diff: "정밀",
        time: 12,
        docs: ["R&D 인력", "기술 내역", "재무제표"],
        fields: [
          { key: "rdPersonnel", label: "R&D 전담 인력 수", type: "number", placeholder: "예: 10" },
          { key: "rdBudget", label: "연간 R&D 예산 (만원)", type: "number", placeholder: "예: 100000" },
          { key: "techField", label: "기술 분야", type: "select", options: ["ICT/SW", "바이오/헬스", "소재/부품", "에너지/환경", "기계/로봇", "우주/항공", "기타"] },
          { key: "priorRdProject", label: "정부 R&D 수행 이력", type: "select", options: ["없음", "1~2건", "3~5건", "6건 이상"] },
          { key: "revenue", label: "최근 연 매출 (만원)", type: "number", placeholder: "예: 500000" },
          { key: "companySize", label: "기업 규모", type: "select", options: ["소기업", "중기업", "중견기업", "대기업"] },
          { key: "hasResearchInstitute", label: "기업부설연구소 보유", type: "select", options: ["보유", "연구전담부서", "미보유"] },
          { key: "patentCount", label: "관련 특허 보유 건수", type: "number", placeholder: "예: 5" },
        ],
        considerations: [
          "기업부설연구소 또는 연구전담부서 설치 인정 여부",
          "과제 유형별 기업 규모 제한 (중소기업 전용, 중견기업 참여 가능 등)",
          "기존 정부 과제 수행 실적 및 성실수행 이력",
          "참여제한 기업 해당 여부 (부정수급, 성실의무 위반 등)",
          "기술 분야별 국가전략기술 해당 여부 및 가점",
        ],
        references: [
          { name: "중소벤처기업부", url: "https://www.mss.go.kr" },
          { name: "한국산업기술평가관리원 (KEIT)", url: "https://www.keit.re.kr" },
          { name: "창업진흥원", url: "https://www.k-startup.go.kr" },
          { name: "기술보증기금", url: "https://www.kibo.or.kr" },
        ],
      },
      {
        name: "수출 바우처 자격",
        desc: "수출 바우처 사업 참여 자격 진단",
        diff: "표준",
        time: 5,
        docs: ["수출 실적", "사업자등록증"],
        fields: [
          { key: "exportAmount", label: "최근 연 수출액 (만 달러)", type: "number", placeholder: "예: 50" },
          { key: "revenue", label: "연 매출 (만원)", type: "number", placeholder: "예: 100000" },
          { key: "companySize", label: "기업 규모", type: "select", options: ["소기업", "중기업", "중견기업"] },
          { key: "exportExperience", label: "수출 경험", type: "select", options: ["수출 경험 없음", "간접수출만", "직접수출 1년 미만", "직접수출 1년 이상"] },
          { key: "targetMarket", label: "목표 시장", type: "select", options: ["동남아", "미주", "유럽", "중국", "일본", "중동", "기타"] },
          { key: "productType", label: "수출 품목 유형", type: "select", options: ["소비재", "산업재", "IT/SW", "농식품", "문화콘텐츠", "서비스", "기타"] },
        ],
        considerations: [
          "수출액 기준: 내국신용장·구매확인서 실적 포함 직·간접 수출 실적",
          "중소·중견기업 해당 여부 (대기업 참여 제한)",
          "수출 초보 기업(수출액 10만 달러 미만) 우대 적용 가능 여부",
          "동일 사업 중복 참여 제한 확인",
        ],
        references: [
          { name: "중소벤처기업부", url: "https://www.mss.go.kr" },
          { name: "KOTRA (대한무역투자진흥공사)", url: "https://www.kotra.or.kr" },
          { name: "소상공인진흥공단", url: "https://www.semas.or.kr" },
        ],
      },
      {
        name: "코스닥 상장 요건 진단",
        desc: "코스닥 상장 요건 충족 여부 진단",
        diff: "정밀",
        time: 20,
        docs: ["재무제표 3개년", "감사보고서", "지배구조 현황"],
        fields: [
          { key: "revenue", label: "최근 연 매출 (억원)", type: "number", placeholder: "예: 300" },
          { key: "netIncome", label: "최근 당기순이익 (억원)", type: "number", placeholder: "예: 30" },
          { key: "equity", label: "자기자본 (억원)", type: "number", placeholder: "예: 100" },
          { key: "listingTrack", label: "상장 트랙", type: "select", options: ["일반기업", "기술성장기업(기술특례)", "이익미실현기업(테슬라요건)"] },
          { key: "auditOpinion", label: "최근 감사의견", type: "select", options: ["적정", "한정", "부적정", "의견거절"] },
          { key: "majorShareholder", label: "최대주주 지분율 (%)", type: "number", placeholder: "예: 35" },
          { key: "isVenture", label: "벤처기업 인증 여부", type: "select", options: ["인증", "미인증"] },
        ],
        considerations: [
          "일반기업: 자기자본 30억 이상, 세전이익 20억(또는 매출 100억+시총 300억) 등 요건 충족",
          "기술특례: 전문평가기관 기술성 평가 A등급 이상 또는 BB등급+자기자본 10억",
          "최근 사업연도 감사의견 적정 필수",
          "최대주주 등 의무보유(보호예수) 기간 6개월~1년",
          "소액주주 분산 요건: 500인 이상, 25% 이상 공모",
        ],
        references: [
          { name: "한국거래소", url: "https://www.krx.co.kr" },
          { name: "중소벤처기업부", url: "https://www.mss.go.kr" },
          { name: "한국벤처투자", url: "https://www.kvic.or.kr" },
        ],
      },
      {
        name: "벤처투자 유치 가능성",
        desc: "벤처캐피탈 투자 유치 가능성 진단",
        diff: "정밀",
        time: 15,
        docs: ["사업계획서", "재무제표", "팀 구성", "시장 분석"],
        fields: [
          { key: "stage", label: "투자 라운드", type: "select", options: ["Pre-Seed", "Seed", "Series A", "Series B", "Series C 이상"] },
          { key: "targetAmount", label: "목표 투자금 (억원)", type: "number", placeholder: "예: 30" },
          { key: "revenue", label: "최근 연 매출 (만원)", type: "number", placeholder: "예: 100000" },
          { key: "growthRate", label: "매출 성장률 (%)", type: "number", placeholder: "예: 200" },
          { key: "market", label: "타겟 시장 규모 (억원)", type: "number", placeholder: "예: 10000" },
          { key: "teamExperience", label: "핵심팀 관련 경력", type: "select", options: ["10년 이상", "5~10년", "3~5년", "3년 미만"] },
          { key: "priorFunding", label: "기존 투자 유치 금액 (억원)", type: "number", placeholder: "예: 5" },
          { key: "techDifferentiation", label: "기술 차별화 수준", type: "select", options: ["독보적(특허)", "우수", "보통", "없음"] },
        ],
        considerations: [
          "투자 라운드별 기대 매출·지표 수준 (Seed: PMF 검증, Series A: 매출 성장, Series B: 수익화)",
          "TAM/SAM/SOM 시장 규모 및 성장률에 따른 투자 매력도",
          "핵심 팀 구성원의 도메인 전문성 및 연쇄창업자 여부",
          "기존 투자자 구성 및 후속 투자 가능성",
          "Exit 전략 (IPO, M&A) 현실성",
        ],
        references: [
          { name: "한국벤처투자", url: "https://www.kvic.or.kr" },
          { name: "중소벤처기업부", url: "https://www.mss.go.kr" },
          { name: "한국벤처캐피탈협회", url: "https://www.kvca.or.kr" },
          { name: "창업진흥원", url: "https://www.k-startup.go.kr" },
        ],
      },
      {
        name: "ISO 인증 적합성",
        desc: "ISO 9001/14001/27001 인증 적합성 진단",
        diff: "표준",
        time: 10,
        docs: ["품질관리 체계", "프로세스 문서", "조직 현황"],
        fields: [
          { key: "targetISO", label: "목표 ISO 인증", type: "select", options: ["ISO 9001 (품질)", "ISO 14001 (환경)", "ISO 27001 (정보보안)", "ISO 45001 (안전보건)", "복수 인증"] },
          { key: "employees", label: "전체 직원 수", type: "number", placeholder: "예: 50" },
          { key: "hasQMS", label: "품질관리시스템 운영 여부", type: "select", options: ["체계적 운영 중", "부분적 운영", "미운영"] },
          { key: "documentLevel", label: "프로세스 문서화 수준", type: "select", options: ["상 (전사 표준화)", "중 (주요 프로세스)", "하 (미비)"] },
          { key: "priorAudit", label: "외부 심사 경험", type: "select", options: ["ISO 인증 보유", "타 인증 보유", "심사 경험 없음"] },
          { key: "budget", label: "인증 예산 (만원)", type: "number", placeholder: "예: 3000" },
        ],
        considerations: [
          "인증 범위 (전사 vs 특정 사업부) 설정의 적절성",
          "현재 프로세스 문서화 수준과 인증 요구사항 간 Gap 분석",
          "내부 심사원 양성 또는 외부 컨설팅 필요 여부",
          "인증 취득 후 사후심사(매년) 및 갱신심사(3년) 유지 비용 고려",
        ],
        references: [
          { name: "한국인정지원센터 (KAB)", url: "https://www.kab.or.kr" },
          { name: "중소벤처기업부", url: "https://www.mss.go.kr" },
          { name: "기술보증기금", url: "https://www.kibo.or.kr" },
        ],
      },
    ],
  },

  daily: {
    personal: [
      {
        name: "운전면허 적성검사",
        desc: "운전면허 적성검사 통과 가능성 진단",
        diff: "간편",
        time: 2,
        docs: ["건강 정보", "시력 정보"],
        fields: [
          { key: "licenseType", label: "면허 종류", type: "select", options: ["1종 보통", "1종 대형", "2종 보통", "2종 소형", "원동기"] },
          { key: "age", label: "나이", type: "number", placeholder: "예: 35" },
          { key: "visionLeft", label: "좌안 시력", type: "number", placeholder: "예: 0.8" },
          { key: "visionRight", label: "우안 시력", type: "number", placeholder: "예: 1.0" },
          { key: "colorBlind", label: "색각 이상 여부", type: "select", options: ["정상", "색약", "색맹"] },
          { key: "hearingIssue", label: "청력 이상 여부", type: "select", options: ["정상", "경미한 난청", "보청기 사용", "심한 난청"] },
          { key: "physicalDisability", label: "신체 장애 여부", type: "select", options: ["없음", "상지 장애", "하지 장애", "기타"] },
        ],
        considerations: [
          "1종: 양쪽 눈 각 0.5 이상, 2종: 양쪽 눈 함께 0.5 이상 (한쪽 실명시 다른 눈 0.6 이상)",
          "55dB 소리를 들을 수 있어야 하며, 보청기 사용 가능",
          "색각 이상은 신호등 색상 구분 가능하면 합격",
          "만 65세 이상 1종 대형/특수면허는 적성검사 주기 단축",
        ],
        references: [
          { name: "정부24 운전면허 적성검사", url: "https://www.gov.kr" },
          { name: "도로교통공단", url: "https://www.koroad.or.kr" },
        ],
      },
      {
        name: "여권 발급 적격",
        desc: "여권 발급·갱신 적격 여부 진단",
        diff: "간편",
        time: 2,
        docs: ["신분증", "병역 관련 서류"],
        fields: [
          { key: "age", label: "나이", type: "number", placeholder: "예: 28" },
          { key: "gender", label: "성별", type: "select", options: ["남성", "여성"] },
          { key: "militaryStatus", label: "병역 상태 (남성)", type: "select", options: ["해당없음", "미필", "복무 중", "전역", "면제", "보충역"] },
          { key: "passportType", label: "여권 유형", type: "select", options: ["일반 여권(10년)", "일반 여권(5년)", "긴급 여권", "관용 여권"] },
          { key: "hasExpired", label: "기존 여권 상태", type: "select", options: ["신규 발급", "유효기간 만료", "유효기간 내 갱신", "분실 재발급"] },
          { key: "criminalRecord", label: "출국금지 해당 여부", type: "select", options: ["해당없음", "형사사건 계류", "세금 체납", "기타 사유"] },
        ],
        considerations: [
          "만 18세 이상 남성: 병역 미필자는 여권 유효기간 5년 이하 제한",
          "국외여행 허가 대상자(현역, 사회복무요원 등)는 병무청 허가 필요",
          "출국금지 대상자(형사사건, 고액 체납 등)는 여권 발급 제한",
          "만 18세 미만 미성년자는 법정대리인 동의 필요",
        ],
        references: [
          { name: "정부24 여권 발급", url: "https://www.gov.kr" },
          { name: "병무청", url: "https://www.mma.go.kr" },
          { name: "외교부 여권안내", url: "https://www.passport.go.kr" },
        ],
      },
      {
        name: "비자 승인 가능성",
        desc: "각국 비자 승인 가능성 시뮬레이션",
        diff: "표준",
        time: 7,
        docs: ["여권", "재정 증빙", "방문 목적", "초청장"],
        fields: [
          { key: "destination", label: "목적국", type: "select", options: ["미국", "일본", "중국", "캐나다", "호주", "영국", "EU/쉥겐", "동남아", "기타"] },
          { key: "visaType", label: "비자 유형", type: "select", options: ["관광(B)", "취업(H/E)", "유학(F)", "사업(B1)", "투자(E2)", "워킹홀리데이(H1)", "기타"] },
          { key: "annualIncome", label: "연 소득 (만원)", type: "number", placeholder: "예: 5000" },
          { key: "bankBalance", label: "예금 잔액 (만원)", type: "number", placeholder: "예: 3000" },
          { key: "travelHistory", label: "선진국 방문 이력", type: "select", options: ["5회 이상", "2~4회", "1회", "없음"] },
          { key: "rejectionHistory", label: "비자 거절 이력", type: "select", options: ["없음", "1회", "2회 이상"] },
          { key: "purpose", label: "방문 목적 상세", type: "text", placeholder: "예: 학회 참석, 어학연수 등" },
        ],
        considerations: [
          "국가별 비자 면제 협정 해당 여부 (한국 여권 무비자 입국 가능 국가)",
          "재정 증빙 충분성: 체류 기간 대비 충분한 자금 보유 여부",
          "이전 비자 거절 이력이 있는 경우 재신청 시 불리하게 작용",
          "출입국 이력 및 체류 이탈 이력 여부",
          "초청장·입학허가서 등 목적 증빙 서류 완비 여부",
        ],
        references: [
          { name: "출입국관리사무소", url: "https://www.immigration.go.kr" },
          { name: "외교부 해외안전여행", url: "https://www.0404.go.kr" },
          { name: "정부24", url: "https://www.gov.kr" },
        ],
      },
      {
        name: "아파트 청약 당첨 확률",
        desc: "아파트 청약 당첨 확률 시뮬레이션",
        diff: "표준",
        time: 5,
        docs: ["청약통장 정보", "가점 항목", "희망 단지"],
        fields: [
          { key: "region", label: "청약 지역", type: "select", options: ["서울", "경기(과밀억제)", "인천", "부산", "대구", "대전", "광주", "세종", "기타"] },
          { key: "houselessPeriod", label: "무주택 기간 (년)", type: "number", placeholder: "예: 10" },
          { key: "dependents", label: "부양가족 수", type: "number", placeholder: "예: 3" },
          { key: "subscriptionPeriod", label: "청약통장 가입 기간 (년)", type: "number", placeholder: "예: 8" },
          { key: "subscriptionBalance", label: "청약통장 납입 총액 (만원)", type: "number", placeholder: "예: 1500" },
          { key: "supplyType", label: "공급 유형", type: "select", options: ["일반공급(가점)", "일반공급(추첨)", "특별공급(신혼)", "특별공급(생애최초)", "특별공급(다자녀)"] },
          { key: "income", label: "월 평균 소득 (만원)", type: "number", placeholder: "예: 400" },
        ],
        considerations: [
          "가점제: 무주택기간(32점) + 부양가족(35점) + 청약통장 가입기간(17점) = 총 84점 만점",
          "투기과열지구 85m2 이하 100% 가점제, 추첨제 비중은 지역·면적별 상이",
          "특별공급: 소득 기준, 자산 기준, 해당 자격(신혼·다자녀 등) 충족 필수",
          "예치금 기준: 지역별·면적별 최소 납입 인정 금액 확인",
          "1순위 자격: 가입 기간(수도권 12개월, 비수도권 6개월) + 납입 횟수",
        ],
        references: [
          { name: "정부24", url: "https://www.gov.kr" },
          { name: "한국부동산원 청약홈", url: "https://www.applyhome.co.kr" },
          { name: "국토교통부", url: "https://www.molit.go.kr" },
        ],
      },
      {
        name: "군 면제/감면 판정",
        desc: "병역 면제·감면 가능성 시뮬레이션",
        diff: "표준",
        time: 5,
        docs: ["건강 정보", "가족 상황", "학력 정보"],
        fields: [
          { key: "age", label: "나이", type: "number", placeholder: "예: 20" },
          { key: "healthGrade", label: "신체등급 (예상)", type: "select", options: ["1급", "2급", "3급", "4급", "5급", "6급", "7급"] },
          { key: "condition", label: "주요 질환/장애", type: "text", placeholder: "예: 시력 저하, 관절 질환 등" },
          { key: "familyStatus", label: "가족 상황", type: "select", options: ["일반", "독자", "가족 부양(부모 질환)", "형제 군복무 중", "다문화가정"] },
          { key: "education", label: "최종 학력", type: "select", options: ["고등학교 졸업", "대학교 재학", "대학교 졸업", "대학원 재학/졸업"] },
          { key: "specialSkill", label: "전문자격/기술", type: "text", placeholder: "예: 의사, 변호사, 박사, 올림픽 메달 등" },
        ],
        considerations: [
          "신체등급 4급: 보충역(사회복무요원), 5급: 전시근로역(면제에 준함), 6급: 병역면제",
          "독자(외아들): 보충역 편입 가능 (신청 시)",
          "전문연구요원·산업기능요원 등 대체복무 자격 해당 여부",
          "병역판정검사 재검사 신청 요건 및 절차",
        ],
        references: [
          { name: "병무청", url: "https://www.mma.go.kr" },
          { name: "정부24", url: "https://www.gov.kr" },
          { name: "국방부", url: "https://www.mnd.go.kr" },
        ],
      },
      {
        name: "귀화 심사 자격",
        desc: "대한민국 귀화 심사 자격 진단",
        diff: "정밀",
        time: 10,
        docs: ["체류 기간", "소득 증빙", "한국어 능력", "범죄 이력"],
        fields: [
          { key: "nationality", label: "현재 국적", type: "text", placeholder: "예: 중국, 베트남 등" },
          { key: "residencePeriod", label: "한국 체류 기간 (년)", type: "number", placeholder: "예: 7" },
          { key: "visaStatus", label: "현재 체류 자격", type: "select", options: ["결혼이민(F-6)", "영주(F-5)", "거주(F-2)", "취업(E계열)", "유학(D-2)", "기타"] },
          { key: "koreanLevel", label: "한국어 능력 (TOPIK)", type: "select", options: ["6급", "5급", "4급", "3급", "2급", "1급", "미응시"] },
          { key: "annualIncome", label: "연 소득 (만원)", type: "number", placeholder: "예: 3000" },
          { key: "criminalRecord", label: "범죄 이력", type: "select", options: ["없음", "경미 (벌금형)", "있음"] },
          { key: "maritalStatus", label: "한국인 배우자 여부", type: "select", options: ["한국인 배우자 있음", "없음"] },
          { key: "hasMinorChild", label: "한국 국적 미성년 자녀", type: "select", options: ["있음", "없음"] },
        ],
        considerations: [
          "일반귀화: 5년 이상 계속 거주, 만 18세 이상, 생계 능력, 한국어 능력, 품행 단정",
          "간이귀화(배우자): 혼인 후 2년 이상 거주 또는 혼인 후 3년 경과+1년 거주",
          "귀화적격 심사에 한국어 필기시험 및 면접 포함",
          "국적법상 이중국적 허용 범위 및 국적 상실 절차",
          "범죄 이력이 있는 경우 품행 요건 불충족 가능성",
        ],
        references: [
          { name: "출입국관리사무소", url: "https://www.immigration.go.kr" },
          { name: "정부24", url: "https://www.gov.kr" },
          { name: "법무부 국적과", url: "https://www.moj.go.kr" },
        ],
      },
      {
        name: "국가장학금 수급 자격",
        desc: "국가장학금 수급 자격 및 금액 시뮬레이션",
        diff: "간편",
        time: 3,
        docs: ["소득분위", "성적", "재학 정보"],
        fields: [
          { key: "incomeLevel", label: "소득 분위 (구간)", type: "select", options: ["1구간", "2구간", "3구간", "4구간", "5구간", "6구간", "7구간", "8구간", "9구간", "10구간"] },
          { key: "gpa", label: "직전 학기 성적 (4.5 만점)", type: "number", placeholder: "예: 3.5" },
          { key: "schoolType", label: "학교 유형", type: "select", options: ["4년제 대학", "전문대(3년)", "전문대(2년)", "원격대학", "학점은행제"] },
          { key: "semester", label: "현재 학기", type: "select", options: ["1학기", "2학기", "3학기", "4학기", "5학기 이상", "신입학/편입학"] },
          { key: "registeredCredits", label: "이수 학점", type: "number", placeholder: "예: 18" },
          { key: "scholarshipType", label: "신청 유형", type: "select", options: ["I유형 (소득연계)", "II유형 (대학연계)", "다자녀", "지역인재"] },
        ],
        considerations: [
          "소득 8구간 이하 지원 가능, 구간별 지원 금액 차등 (1구간: 전액, 8구간: 일부)",
          "직전 학기 12학점 이상 이수 및 평점 B학점(80점/100점) 이상 성적 기준",
          "신입생·편입생은 첫 학기 성적 기준 미적용",
          "등록횟수 제한: 4년제 8회, 3년제 6회, 2년제 4회",
        ],
        references: [
          { name: "한국장학재단", url: "https://www.kosaf.go.kr" },
          { name: "정부24", url: "https://www.gov.kr" },
        ],
      },
      {
        name: "공무원 시험 가산점 계산",
        desc: "공무원 시험 가산점 시뮬레이션",
        diff: "간편",
        time: 2,
        docs: ["자격증", "군 경력", "기타 가점 항목"],
        fields: [
          { key: "examType", label: "시험 유형", type: "select", options: ["9급 공채", "7급 공채", "경찰 공채", "소방 공채", "군무원", "기타"] },
          { key: "certificates", label: "보유 자격증", type: "text", placeholder: "예: 정보처리기사, 한국사능력검정1급" },
          { key: "militaryService", label: "군 복무 형태", type: "select", options: ["해당없음", "의무복무(현역)", "의무복무(사회복무)", "직업군인", "전투 경험"] },
          { key: "militaryPeriod", label: "군 복무 기간 (개월)", type: "number", placeholder: "예: 18" },
          { key: "disabilityGrade", label: "장애 등급", type: "select", options: ["해당없음", "경증(6~3급)", "중증(2~1급)"] },
          { key: "lowIncome", label: "저소득층 해당 여부", type: "select", options: ["해당없음", "기초생활수급자", "차상위계층"] },
        ],
        considerations: [
          "자격증 가산점: 직렬별 가산 적용 자격증 목록 확인 (5% 또는 3%)",
          "군 가산점: 의무복무 완료자 만점의 5% 또는 3% 가산 (2년 이상/2년 미만)",
          "취업지원대상자: 국가유공자 등은 만점의 5% 또는 10% 가산",
          "가산점 합산 한도: 개별 과목 만점의 40% 초과 불가",
        ],
        references: [
          { name: "인사혁신처", url: "https://www.mpm.go.kr" },
          { name: "정부24", url: "https://www.gov.kr" },
          { name: "사이버국가고시센터", url: "https://gosi.kr" },
        ],
      },
      {
        name: "주민등록 주소이전 적격",
        desc: "주민등록 주소이전 가능 여부 진단",
        diff: "간편",
        time: 2,
        docs: ["현 주소", "이전 주소", "거주 사실 확인"],
        fields: [
          { key: "moveReason", label: "이전 사유", type: "select", options: ["실제 이사", "전입 (타 시도)", "세대 분리", "세대 합가", "기타"] },
          { key: "currentAddress", label: "현재 주소 시도", type: "select", options: ["서울", "경기", "인천", "부산", "대구", "대전", "광주", "세종", "강원", "충북", "충남", "전북", "전남", "경북", "경남", "제주"] },
          { key: "newAddress", label: "이전 주소 시도", type: "select", options: ["서울", "경기", "인천", "부산", "대구", "대전", "광주", "세종", "강원", "충북", "충남", "전북", "전남", "경북", "경남", "제주"] },
          { key: "residenceProof", label: "거주 사실 증빙", type: "select", options: ["임대차계약서", "등기부등본(자가)", "거주사실확인서", "기타"] },
          { key: "householdHead", label: "세대주 여부", type: "select", options: ["세대주", "세대원"] },
        ],
        considerations: [
          "전입신고 기한: 이사 후 14일 이내 신고 의무 (위반 시 과태료 5만원)",
          "실제 거주지와 다른 주소로의 위장전입은 주민등록법 위반",
          "학군 배정, 청약 등 목적의 허위 전입 시 법적 제재 가능",
          "세대 분리 시 동일 주소지에서도 가능하나 실질적 독립 생계 요건 필요",
        ],
        references: [
          { name: "정부24 전입신고", url: "https://www.gov.kr" },
          { name: "행정안전부", url: "https://www.mois.go.kr" },
        ],
      },
    ],
    sole: [
      {
        name: "영업허가 적격",
        desc: "업종별 영업허가 적격 여부 진단",
        diff: "표준",
        time: 5,
        docs: ["업종 정보", "시설 정보", "위치 정보"],
        fields: [
          { key: "businessType", label: "업종", type: "select", options: ["일반음식점", "휴게음식점", "제과점", "유통업", "학원", "미용업", "숙박업", "기타"] },
          { key: "area", label: "영업장 면적 (m2)", type: "number", placeholder: "예: 50" },
          { key: "location", label: "영업장 위치", type: "text", placeholder: "예: 서울 강남구 역삼동" },
          { key: "zoning", label: "용도지역", type: "select", options: ["상업지역", "준주거지역", "일반주거지역", "공업지역", "기타/모름"] },
          { key: "hasParking", label: "주차장 확보", type: "select", options: ["확보", "부분 확보", "미확보"] },
          { key: "facilityReady", label: "시설 기준 충족", type: "select", options: ["충족", "일부 미비", "미확인"] },
          { key: "ownerCertificate", label: "대표자 자격증", type: "select", options: ["해당없음", "위생교육 이수", "관련 자격증 보유", "미이수"] },
        ],
        considerations: [
          "업종별 시설 기준: 조리장 면적, 환기설비, 급배수 시설 등 법정 요건",
          "용도지역별 영업 가능 업종 제한 (주거지역 내 유흥업 불가 등)",
          "학교정화구역(200m) 내 업종 제한 확인",
          "대표자 위생교육 이수 필수 (영업 시작 전)",
          "건축물대장상 용도와 실제 영업 용도 일치 여부",
        ],
        references: [
          { name: "정부24 영업허가", url: "https://www.gov.kr" },
          { name: "식약처", url: "https://www.mfds.go.kr" },
          { name: "각 지자체 위생과", url: "https://www.gov.kr" },
        ],
      },
      {
        name: "식품위생 적합성",
        desc: "식품위생법 적합 여부 진단",
        diff: "표준",
        time: 5,
        docs: ["시설 현황", "위생관리 체계", "영업 유형"],
        fields: [
          { key: "foodType", label: "식품 유형", type: "select", options: ["일반음식점", "즉석판매제조가공업", "식품제조가공업", "집단급식소", "건강기능식품", "기타"] },
          { key: "hasHACCP", label: "HACCP 인증 여부", type: "select", options: ["인증 보유", "준비 중", "미적용"] },
          { key: "kitchenArea", label: "조리장/제조실 면적 (m2)", type: "number", placeholder: "예: 30" },
          { key: "waterSupply", label: "급수 시설", type: "select", options: ["상수도", "지하수(수질검사 완료)", "지하수(미검사)"] },
          { key: "coldChain", label: "냉장/냉동 설비", type: "select", options: ["완비", "부분 보유", "미보유"] },
          { key: "hygieneTraining", label: "위생교육 이수 여부", type: "select", options: ["이수 완료", "미이수"] },
        ],
        considerations: [
          "조리장과 객석 구분, 환기시설, 방충·방서 설비 등 시설 기준 충족",
          "급수 시설: 지하수 사용 시 수질검사 성적서 필수 (먹는물 수질기준)",
          "식품등의 표시기준 준수 (제조일, 유통기한, 원재료 등)",
          "영업자 및 종업원 건강진단 실시 (연 1회)",
          "HACCP 의무 적용 대상 여부 확인 (매출 규모별)",
        ],
        references: [
          { name: "식약처", url: "https://www.mfds.go.kr" },
          { name: "정부24", url: "https://www.gov.kr" },
          { name: "한국식품안전관리인증원", url: "https://www.haccp.or.kr" },
        ],
      },
      {
        name: "주류 면허 자격",
        desc: "주류 판매/제조 면허 자격 진단",
        diff: "표준",
        time: 5,
        docs: ["사업 계획", "시설 정보", "위치 정보"],
        fields: [
          { key: "licenseType", label: "면허 유형", type: "select", options: ["종합주류도매", "주류소매", "유흥음식점 주류판매", "주류제조", "통신판매(전통주)"] },
          { key: "businessType", label: "영업 유형", type: "select", options: ["음식점", "편의점/마트", "주류전문점", "온라인몰", "제조업", "기타"] },
          { key: "area", label: "매장/제조시설 면적 (m2)", type: "number", placeholder: "예: 40" },
          { key: "capital", label: "자본금 (만원)", type: "number", placeholder: "예: 5000" },
          { key: "location", label: "사업장 위치", type: "text", placeholder: "예: 서울 마포구 홍대" },
          { key: "priorViolation", label: "주세법 위반 이력", type: "select", options: ["없음", "있음"] },
        ],
        considerations: [
          "주류 소매면허: 시설·거리 제한(학교 200m 등), 면적 기준 충족 필요",
          "종합주류도매: 자본금 기준(1억 이상) 및 시설 기준 충족",
          "전통주 통신판매: 전통주만 온라인 판매 가능, 일반주류 통신판매 금지",
          "주세법 위반 전력(면허 취소 후 2년 이내) 시 면허 발급 제한",
        ],
        references: [
          { name: "국세청 주류면허", url: "https://www.nts.go.kr" },
          { name: "정부24", url: "https://www.gov.kr" },
          { name: "식약처", url: "https://www.mfds.go.kr" },
        ],
      },
    ],
    corp: [
      {
        name: "산업안전 적합성",
        desc: "산업안전보건법 적합성 진단",
        diff: "정밀",
        time: 12,
        docs: ["안전관리 체계", "시설 현황", "사고 이력"],
        fields: [
          { key: "industry", label: "업종", type: "select", options: ["건설업", "제조업", "화학공업", "물류/운송", "서비스업", "광업", "기타"] },
          { key: "employees", label: "상시 근로자 수", type: "number", placeholder: "예: 100" },
          { key: "hasSafetyOfficer", label: "안전관리자 선임", type: "select", options: ["선임 완료", "미선임"] },
          { key: "hasHealthOfficer", label: "보건관리자 선임", type: "select", options: ["선임 완료", "미선임"] },
          { key: "accidentHistory", label: "최근 3년 산재 이력", type: "select", options: ["없음", "1건", "2~3건", "4건 이상", "사망사고 포함"] },
          { key: "hasMSDS", label: "화학물질 MSDS 비치", type: "select", options: ["해당없음", "비치 완료", "일부 미비", "미비치"] },
          { key: "safetyBudget", label: "안전보건 예산 (만원/년)", type: "number", placeholder: "예: 5000" },
          { key: "riskAssessment", label: "위험성평가 실시 여부", type: "select", options: ["정기 실시", "1회 실시", "미실시"] },
        ],
        considerations: [
          "50인 이상 사업장: 안전관리자·보건관리자 선임 의무",
          "중대재해처벌법: 상시근로자 50인 이상(2024~ 5인 이상) 적용",
          "위험성평가 의무 실시 및 기록 보관 (산안법 제36조)",
          "안전보건교육 실시 의무: 정기교육, 채용 시 교육, 작업내용 변경 시 교육",
          "산업재해율에 따른 산재보험료 할증 가능성",
        ],
        references: [
          { name: "한국산업안전보건공단 (KOSHA)", url: "https://www.kosha.or.kr" },
          { name: "고용노동부", url: "https://www.moel.go.kr" },
          { name: "정부24", url: "https://www.gov.kr" },
        ],
      },
      {
        name: "환경영향 평가",
        desc: "환경영향평가 적합성 사전 진단",
        diff: "정밀",
        time: 15,
        docs: ["사업 규모", "오염물질 배출", "입지 정보"],
        fields: [
          { key: "projectType", label: "사업 유형", type: "select", options: ["공장 설립", "택지 개발", "도로 건설", "산업단지 조성", "관광단지", "에너지 시설", "폐기물 처리", "기타"] },
          { key: "projectArea", label: "사업 면적 (m2)", type: "number", placeholder: "예: 50000" },
          { key: "emissionType", label: "주요 배출 오염물질", type: "select", options: ["대기오염물질", "수질오염물질", "폐기물", "소음/진동", "복합", "해당없음"] },
          { key: "location", label: "사업 입지", type: "text", placeholder: "예: 경기도 화성시 OO동" },
          { key: "nearProtectedArea", label: "보호구역 인접 여부", type: "select", options: ["해당없음", "상수원보호구역", "자연공원", "습지보호지역", "생태경관보전지역"] },
          { key: "investmentAmount", label: "총 사업비 (억원)", type: "number", placeholder: "예: 500" },
          { key: "expectedDuration", label: "사업 기간 (년)", type: "number", placeholder: "예: 5" },
        ],
        considerations: [
          "환경영향평가 대상: 사업 유형 및 규모별 법정 기준 초과 시 의무",
          "소규모 환경영향평가: 보전용도지역 5천m2 이상, 비보전 1만m2 이상 등",
          "전략환경영향평가: 개발기본계획 수립 단계에서 실시",
          "주민 공람·공청회 등 주민 참여 절차 이행 필수",
          "환경영향평가서 부실 작성 시 반려·보완 요구 및 과태료",
        ],
        references: [
          { name: "환경부", url: "https://www.me.go.kr" },
          { name: "한국환경연구원", url: "https://www.kei.re.kr" },
          { name: "환경영향평가 정보지원시스템 (EIASS)", url: "https://www.eiass.go.kr" },
        ],
      },
      {
        name: "개인정보 보호 적합성",
        desc: "개인정보보호법 적합성 진단",
        diff: "표준",
        time: 7,
        docs: ["개인정보 처리 현황", "보안 체계", "위탁 현황"],
        fields: [
          { key: "dataSubjects", label: "개인정보 처리 규모 (건)", type: "number", placeholder: "예: 50000" },
          { key: "dataType", label: "수집 개인정보 유형", type: "select", options: ["일반 개인정보", "고유식별정보(주민번호 등)", "민감정보(건강, 사상 등)", "복합"] },
          { key: "hasCPO", label: "개인정보보호 책임자(CPO)", type: "select", options: ["선임 완료", "미선임"] },
          { key: "hasPrivacyPolicy", label: "개인정보 처리방침 공개", type: "select", options: ["웹사이트 게시", "미게시"] },
          { key: "encryptionLevel", label: "암호화 수준", type: "select", options: ["전송+저장 암호화", "전송만 암호화", "암호화 미적용"] },
          { key: "thirdPartySharing", label: "제3자 제공 여부", type: "select", options: ["없음", "국내 제공", "국외 이전 포함"] },
          { key: "hasConsent", label: "정보주체 동의 절차", type: "select", options: ["전자적 동의", "서면 동의", "미비"] },
        ],
        considerations: [
          "개인정보 처리방침 필수 공개 항목 9가지 충족 여부",
          "개인정보 처리 위탁 시 수탁자 관리·감독 의무 이행",
          "고유식별정보·민감정보 처리 시 별도 동의 및 암호화 의무",
          "개인정보 영향평가: 5만 건 이상 민감정보 처리 시 의무",
          "개인정보 유출 통지 의무: 1천 건 이상 유출 시 72시간 내 신고",
        ],
        references: [
          { name: "개인정보보호위원회", url: "https://www.pipc.go.kr" },
          { name: "정부24", url: "https://www.gov.kr" },
          { name: "한국인터넷진흥원 (KISA)", url: "https://www.kisa.or.kr" },
        ],
      },
    ],
  },
};
