// ============================================================
// 무엇이든 심사받으세요 - Enhanced Service Data (법률 / 세무)
// Generated 2026-04-01
// ============================================================

export const DATA_LT = {
  legal: {
    personal: [
      {
        name: "소액재판 승소 가능성",
        desc: "소액사건 승소 확률 및 예상 판결 시뮬레이션",
        diff: "표준",
        time: 7,
        docs: ["분쟁 내용", "증거자료", "청구금액"],
        fields: [
          { key: "claimAmount", label: "청구 금액", type: "number", placeholder: "예: 20000000" },
          { key: "disputeType", label: "분쟁 유형", type: "select", placeholder: "선택", options: ["대여금 반환", "매매대금", "손해배상", "용역대금", "임금체불", "기타"] },
          { key: "evidenceLevel", label: "증거 확보 수준", type: "select", placeholder: "선택", options: ["계약서+입금내역 있음", "계약서만 있음", "문자/카톡만 있음", "구두 약속만", "증인 있음"] },
          { key: "opponentResponse", label: "상대방 반응", type: "select", placeholder: "선택", options: ["무응답", "일부 인정", "전면 부인", "역소 가능성"] },
          { key: "disputePeriod", label: "분쟁 발생 시점", type: "text", placeholder: "예: 2025년 6월" },
          { key: "priorNegotiation", label: "사전 협의 여부", type: "select", placeholder: "선택", options: ["내용증명 발송", "구두 협의 시도", "협의 없음"] },
        ],
        considerations: [
          "소액사건(3,000만원 이하)은 이행권고결정 제도가 적용되어 절차가 간소합니다.",
          "소멸시효(일반 채권 10년, 상사 채권 5년) 경과 여부가 핵심입니다.",
          "증거의 객관성과 연속성(계약서 → 입금내역 → 독촉 기록)이 승소율을 결정합니다.",
          "상대방의 자력(재산 상태)도 실질적 회수 가능성에 영향을 미칩니다.",
        ],
        references: [
          { name: "대법원 판례정보시스템", url: "https://glaw.scourt.go.kr" },
          { name: "법제처 국가법령정보센터", url: "https://www.law.go.kr" },
          { name: "대한법률구조공단", url: "https://www.klac.or.kr" },
        ],
      },
      {
        name: "이혼 재산분할 시뮬레이션",
        desc: "이혼 시 재산분할 비율 및 금액 시뮬레이션",
        diff: "정밀",
        time: 10,
        docs: ["혼인기간", "재산목록", "소득 내역"],
        fields: [
          { key: "marriageDuration", label: "혼인 기간(년)", type: "number", placeholder: "예: 12" },
          { key: "totalAsset", label: "부부 공동재산 총액", type: "number", placeholder: "예: 500000000" },
          { key: "personalAsset", label: "혼전 특유재산 금액", type: "number", placeholder: "예: 100000000" },
          { key: "myIncome", label: "본인 연소득", type: "number", placeholder: "예: 50000000" },
          { key: "spouseIncome", label: "배우자 연소득", type: "number", placeholder: "예: 30000000" },
          { key: "childCount", label: "미성년 자녀 수", type: "number", placeholder: "예: 2" },
          { key: "divorceReason", label: "이혼 사유", type: "select", placeholder: "선택", options: ["성격 차이", "외도", "경제적 문제", "가정 폭력", "기타"] },
          { key: "custodyWish", label: "양육권 희망", type: "select", placeholder: "선택", options: ["본인", "배우자", "협의 중"] },
        ],
        considerations: [
          "혼인 중 형성한 재산은 원칙적으로 부부 공동 노력의 산물로 추정됩니다.",
          "기여도는 경제적 기여뿐 아니라 가사노동, 육아 등 비경제적 기여도 포함합니다.",
          "혼전 특유재산, 상속·증여받은 재산은 분할 대상에서 제외될 수 있습니다.",
          "위자료는 재산분할과 별도로 유책배우자에게 청구 가능합니다.",
          "양육비는 자녀 나이, 부모 소득 등을 종합 고려하여 산정됩니다.",
        ],
        references: [
          { name: "대법원 판례정보시스템", url: "https://glaw.scourt.go.kr" },
          { name: "법제처 국가법령정보센터", url: "https://www.law.go.kr" },
          { name: "대한법률구조공단", url: "https://www.klac.or.kr" },
          { name: "법원 전자소송", url: "https://ecfs.scourt.go.kr" },
        ],
      },
      {
        name: "교통사고 과실비율",
        desc: "교통사고 과실비율 판단 시뮬레이션",
        diff: "표준",
        time: 5,
        docs: ["사고 상황", "블랙박스", "경찰 조서"],
        fields: [
          { key: "accidentType", label: "사고 유형", type: "select", placeholder: "선택", options: ["차대차 추돌", "차대차 교차로", "차대보행자", "차대이륜차", "후진 사고", "주차장 사고", "기타"] },
          { key: "myVehicle", label: "본인 차량 종류", type: "select", placeholder: "선택", options: ["승용차", "SUV", "화물차", "오토바이", "자전거", "보행자"] },
          { key: "signalStatus", label: "신호 상태", type: "select", placeholder: "선택", options: ["본인 녹색", "상대 녹색", "황색 전환 중", "비신호 교차로", "해당없음"] },
          { key: "hasBlackbox", label: "블랙박스 영상", type: "select", placeholder: "선택", options: ["있음(유리)", "있음(불리)", "없음"] },
          { key: "injuryLevel", label: "부상 정도", type: "select", placeholder: "선택", options: ["경상(2주 이하)", "중상(3주 이상)", "중상해", "사망", "물적 피해만"] },
          { key: "accidentDesc", label: "사고 상황 설명", type: "text", placeholder: "구체적인 사고 경위를 입력하세요" },
        ],
        considerations: [
          "과실비율은 대법원 과실비율 인정 기준표를 근거로 판단합니다.",
          "블랙박스 영상은 가장 강력한 증거이며, 없으면 사고접수 보고서가 기준입니다.",
          "음주, 무면허, 과속 등 중과실은 과실비율에 가중 적용됩니다.",
          "보행자 사고는 차량 운전자에게 과실이 높게 적용되는 것이 일반적입니다.",
        ],
        references: [
          { name: "대법원 판례정보시스템", url: "https://glaw.scourt.go.kr" },
          { name: "손해보험협회 과실비율 기준", url: "https://www.knia.or.kr" },
          { name: "법제처 국가법령정보센터", url: "https://www.law.go.kr" },
        ],
      },
      {
        name: "임대차 분쟁 판단",
        desc: "임대차 관련 분쟁 승소 가능성 진단",
        diff: "표준",
        time: 7,
        docs: ["임대차계약서", "분쟁 내용", "증거자료"],
        fields: [
          { key: "disputeCategory", label: "분쟁 유형", type: "select", placeholder: "선택", options: ["보증금 미반환", "일방적 퇴거 요구", "임대료 인상 분쟁", "수선비 분쟁", "원상복구 분쟁", "계약갱신 거절"] },
          { key: "deposit", label: "보증금 금액", type: "number", placeholder: "예: 50000000" },
          { key: "monthlyRent", label: "월 임대료", type: "number", placeholder: "예: 500000" },
          { key: "contractPeriod", label: "계약 기간(년)", type: "number", placeholder: "예: 2" },
          { key: "residencePeriod", label: "실제 거주 기간(개월)", type: "number", placeholder: "예: 18" },
          { key: "hasConfirmDate", label: "확정일자 여부", type: "select", placeholder: "선택", options: ["있음", "없음"] },
          { key: "hasRegistration", label: "전입신고 여부", type: "select", placeholder: "선택", options: ["있음", "없음"] },
        ],
        considerations: [
          "주택임대차보호법상 대항력(전입신고+점유)과 우선변제권(확정일자)이 핵심입니다.",
          "2020년 계약갱신청구권(1회, 총 4년 보장)이 도입되었습니다.",
          "임대료 인상은 5% 상한 규정이 적용됩니다.",
          "보증금 미반환 시 임차권등기명령 제도를 활용할 수 있습니다.",
        ],
        references: [
          { name: "법제처 국가법령정보센터", url: "https://www.law.go.kr" },
          { name: "대한법률구조공단", url: "https://www.klac.or.kr" },
          { name: "법원 전자소송", url: "https://ecfs.scourt.go.kr" },
        ],
      },
      {
        name: "상속세 시뮬레이션",
        desc: "상속 시 세금 및 분할 시뮬레이션",
        diff: "정밀",
        time: 10,
        docs: ["상속재산 목록", "상속인 정보", "채무 내역"],
        fields: [
          { key: "totalEstate", label: "상속재산 총액", type: "number", placeholder: "예: 1000000000" },
          { key: "realEstate", label: "부동산 가액", type: "number", placeholder: "예: 700000000" },
          { key: "financialAsset", label: "금융재산 가액", type: "number", placeholder: "예: 200000000" },
          { key: "debt", label: "피상속인 채무", type: "number", placeholder: "예: 50000000" },
          { key: "heirCount", label: "법정 상속인 수", type: "number", placeholder: "예: 3" },
          { key: "spouseExists", label: "배우자 상속 여부", type: "select", placeholder: "선택", options: ["있음", "없음"] },
          { key: "priorGift", label: "10년 내 사전증여 총액", type: "number", placeholder: "예: 100000000" },
          { key: "oneHousehold", label: "동거주택 상속공제 해당", type: "select", placeholder: "선택", options: ["해당", "비해당"] },
        ],
        considerations: [
          "일괄공제(5억원)와 배우자공제(최소 5억~최대 30억)가 핵심 공제 항목입니다.",
          "사전증여(10년 이내)는 상속재산에 합산됩니다.",
          "동거주택 상속공제(최대 6억)는 10년 이상 동거 요건이 필요합니다.",
          "금융재산 공제(2천만~2억)도 활용 가능합니다.",
          "세율은 1억 이하 10%에서 30억 초과 50%까지 5단계 누진입니다.",
        ],
        references: [
          { name: "국세청 홈택스", url: "https://www.hometax.go.kr" },
          { name: "법제처 국가법령정보센터", url: "https://www.law.go.kr" },
          { name: "대한법률구조공단", url: "https://www.klac.or.kr" },
        ],
      },
      {
        name: "소비자 피해 구제 가능성",
        desc: "소비자 피해 구제 신청 성공 가능성",
        diff: "간편",
        time: 5,
        docs: ["피해 내용", "증빙자료", "판매자 정보"],
        fields: [
          { key: "damageType", label: "피해 유형", type: "select", placeholder: "선택", options: ["제품 하자", "서비스 불이행", "허위 광고", "환불 거부", "개인정보 유출", "안전사고"] },
          { key: "damageAmount", label: "피해 금액", type: "number", placeholder: "예: 500000" },
          { key: "purchaseDate", label: "구매/이용 일자", type: "text", placeholder: "예: 2025-12-01" },
          { key: "evidenceType", label: "증빙자료", type: "select", placeholder: "선택", options: ["영수증+제품", "영수증만", "온라인 주문내역", "사진/영상", "없음"] },
          { key: "sellerResponse", label: "판매자 대응", type: "select", placeholder: "선택", options: ["무응답", "환불 거부", "일부 보상 제안", "책임 부인"] },
        ],
        considerations: [
          "소비자기본법에 따라 1372 소비자상담센터에 먼저 상담을 권장합니다.",
          "한국소비자원 피해구제 신청은 무료이며, 합의 권고까지 약 30일 소요됩니다.",
          "청약철회(온라인 구매 7일 이내)와 하자 담보책임 기간을 확인해야 합니다.",
          "소비자분쟁해결기준(공정거래위원회 고시)이 배상 기준이 됩니다.",
        ],
        references: [
          { name: "한국소비자원", url: "https://www.kca.go.kr" },
          { name: "법제처 국가법령정보센터", url: "https://www.law.go.kr" },
          { name: "1372 소비자상담센터", url: "https://www.ccn.go.kr" },
        ],
      },
      {
        name: "개인회생 적격 심사",
        desc: "개인회생 신청 적격 여부 진단",
        diff: "정밀",
        time: 10,
        docs: ["채무 목록", "소득 증빙", "재산 내역"],
        fields: [
          { key: "totalDebt", label: "총 채무액", type: "number", placeholder: "예: 150000000" },
          { key: "securedDebt", label: "담보채무액", type: "number", placeholder: "예: 50000000" },
          { key: "unsecuredDebt", label: "무담보채무액", type: "number", placeholder: "예: 100000000" },
          { key: "monthlyIncome", label: "월 소득", type: "number", placeholder: "예: 3000000" },
          { key: "monthlyExpense", label: "월 필수 지출", type: "number", placeholder: "예: 1500000" },
          { key: "incomeType", label: "소득 유형", type: "select", placeholder: "선택", options: ["급여소득", "사업소득", "연금소득", "일용직", "기타"] },
          { key: "dependentCount", label: "부양가족 수", type: "number", placeholder: "예: 2" },
        ],
        considerations: [
          "무담보채무 10억 이하, 담보채무 15억 이하인 개인만 신청 가능합니다.",
          "정기적이고 확실한 수입이 있어야 합니다(가용소득으로 변제 가능).",
          "변제기간은 최장 5년(60개월)이며, 최저변제금 이상을 변제해야 합니다.",
          "면책불허가 사유(도박, 사치 등)가 있으면 불이익이 있을 수 있습니다.",
          "개인회생 개시결정 시 채권자의 강제집행이 중지됩니다.",
        ],
        references: [
          { name: "대법원 판례정보시스템", url: "https://glaw.scourt.go.kr" },
          { name: "법원 전자소송", url: "https://ecfs.scourt.go.kr" },
          { name: "대한법률구조공단", url: "https://www.klac.or.kr" },
        ],
      },
      {
        name: "개인파산 면책 가능성",
        desc: "개인파산 면책 결정 가능성 시뮬레이션",
        diff: "정밀",
        time: 10,
        docs: ["채무 목록", "소득 증빙", "파산 원인"],
        fields: [
          { key: "totalDebt", label: "총 채무액", type: "number", placeholder: "예: 300000000" },
          { key: "monthlyIncome", label: "월 소득", type: "number", placeholder: "예: 1500000" },
          { key: "totalAsset", label: "총 자산", type: "number", placeholder: "예: 5000000" },
          { key: "debtCause", label: "주된 채무 원인", type: "select", placeholder: "선택", options: ["생활비 부족", "사업 실패", "보증 채무", "투자 손실", "도박", "과소비", "의료비"] },
          { key: "hasIncome", label: "현재 소득 상태", type: "select", placeholder: "선택", options: ["무직", "일용직", "최저임금 수준", "기초수급자"] },
          { key: "dependentCount", label: "부양가족 수", type: "number", placeholder: "예: 1" },
          { key: "priorBankruptcy", label: "과거 면책 이력", type: "select", placeholder: "선택", options: ["없음", "있음(7년 이상 전)", "있음(7년 이내)"] },
        ],
        considerations: [
          "지급불능 상태(채무변제 불가)가 객관적으로 인정되어야 합니다.",
          "면책불허가 사유(도박·사치·편파변제 등)가 있으면 면책이 거절될 수 있습니다.",
          "다만 재량면책 제도가 있어, 사유가 있더라도 면책될 수 있습니다.",
          "세금, 벌금, 양육비 등 비면책 채권은 파산 후에도 남습니다.",
          "파산선고 후 면책결정까지 약 3~6개월 소요됩니다.",
        ],
        references: [
          { name: "대법원 판례정보시스템", url: "https://glaw.scourt.go.kr" },
          { name: "법원 전자소송", url: "https://ecfs.scourt.go.kr" },
          { name: "대한법률구조공단", url: "https://www.klac.or.kr" },
          { name: "법제처 국가법령정보센터", url: "https://www.law.go.kr" },
        ],
      },
      {
        name: "명예훼손 소송 가능성",
        desc: "명예훼손 소송 승소 가능성 시뮬레이션",
        diff: "표준",
        time: 7,
        docs: ["피해 내용", "증거자료", "상대방 정보"],
        fields: [
          { key: "defamationType", label: "명예훼손 유형", type: "select", placeholder: "선택", options: ["온라인 게시글", "SNS 발언", "언론 보도", "직접 발언(공연성)", "허위사실 유포", "모욕"] },
          { key: "contentTruth", label: "적시 내용의 진실 여부", type: "select", placeholder: "선택", options: ["허위 사실", "사실이지만 명예훼손", "사실 여부 불분명"] },
          { key: "spreadRange", label: "전파 범위", type: "select", placeholder: "선택", options: ["개인 간", "소규모 커뮤니티", "대형 포털/SNS", "언론 보도"] },
          { key: "damageType", label: "피해 유형", type: "select", placeholder: "선택", options: ["정신적 피해", "직업적 피해", "사업상 피해", "사회적 평판 하락"] },
          { key: "evidenceType", label: "증거 종류", type: "select", placeholder: "선택", options: ["스크린샷 있음", "녹음 파일 있음", "증인 있음", "기사 링크", "증거 미확보"] },
          { key: "opponentKnown", label: "상대방 신원 파악", type: "select", placeholder: "선택", options: ["실명 확인", "닉네임만", "신원 불명"] },
        ],
        considerations: [
          "형사상 명예훼손은 공연성(불특정 다수 인식 가능)이 핵심 요건입니다.",
          "허위사실 적시는 7년 이하 징역, 사실 적시는 2년 이하 징역입니다.",
          "온라인 명예훼손은 정보통신망법 적용으로 가중처벌됩니다.",
          "위법성 조각사유(공공의 이익 등)가 인정되면 무죄가 될 수 있습니다.",
        ],
        references: [
          { name: "대법원 판례정보시스템", url: "https://glaw.scourt.go.kr" },
          { name: "법제처 국가법령정보센터", url: "https://www.law.go.kr" },
          { name: "방송통신심의위원회", url: "https://www.kocsc.or.kr" },
        ],
      },
      {
        name: "의료사고 손해배상 가능성",
        desc: "의료사고 손해배상 청구 가능성 진단",
        diff: "정밀",
        time: 10,
        docs: ["진료기록", "의료 과실 정황", "피해 내역"],
        fields: [
          { key: "treatmentType", label: "진료/시술 유형", type: "select", placeholder: "선택", options: ["수술", "약물 투여", "진단 오류", "분만 사고", "마취 사고", "감염", "성형 부작용", "치과 시술"] },
          { key: "damageLevel", label: "피해 정도", type: "select", placeholder: "선택", options: ["경미(일시적)", "중등도(장기 치료)", "중증(후유장애)", "사망"] },
          { key: "medicalRecords", label: "의무기록 확보", type: "select", placeholder: "선택", options: ["전체 확보", "일부 확보", "미확보"] },
          { key: "expertOpinion", label: "전문가 소견", type: "select", placeholder: "선택", options: ["과실 의심 소견 있음", "소견 미확보", "과실 없다는 소견"] },
          { key: "timeSinceAccident", label: "사고 후 경과 기간", type: "text", placeholder: "예: 6개월" },
          { key: "hospitalResponse", label: "병원 측 대응", type: "select", placeholder: "선택", options: ["과실 인정", "과실 부인", "합의 제안", "무응답"] },
          { key: "totalDamage", label: "예상 피해액(치료비 등)", type: "number", placeholder: "예: 30000000" },
        ],
        considerations: [
          "의료과실 입증 책임은 원칙적으로 환자 측에 있지만, 판례상 일정 부분 전환됩니다.",
          "의무기록 확보가 가장 중요하며, 의료법상 열람·복사를 요구할 수 있습니다.",
          "한국의료분쟁조정중재원을 통한 조정 절차도 활용 가능합니다.",
          "손해배상 범위는 치료비, 일실수입, 위자료, 간병비 등을 포함합니다.",
          "의료소송 승소율은 약 30% 내외로, 전문 감정이 중요합니다.",
        ],
        references: [
          { name: "한국의료분쟁조정중재원", url: "https://www.k-medi.or.kr" },
          { name: "대법원 판례정보시스템", url: "https://glaw.scourt.go.kr" },
          { name: "법제처 국가법령정보센터", url: "https://www.law.go.kr" },
          { name: "대한법률구조공단", url: "https://www.klac.or.kr" },
        ],
      },
    ],
    sole: [
      {
        name: "상가 임대차 분쟁",
        desc: "상가 임대차 분쟁 판단 시뮬레이션",
        diff: "표준",
        time: 7,
        docs: ["임대차계약서", "분쟁 내용", "증거자료"],
        fields: [
          { key: "disputeType", label: "분쟁 유형", type: "select", placeholder: "선택", options: ["보증금 미반환", "권리금 회수 방해", "임대료 인상", "계약갱신 거절", "퇴거 요구", "원상복구"] },
          { key: "deposit", label: "보증금", type: "number", placeholder: "예: 50000000" },
          { key: "monthlyRent", label: "월 임대료", type: "number", placeholder: "예: 2000000" },
          { key: "premiumAmount", label: "권리금", type: "number", placeholder: "예: 30000000" },
          { key: "contractYears", label: "총 임차 기간(년)", type: "number", placeholder: "예: 5" },
          { key: "businessType", label: "업종", type: "text", placeholder: "예: 음식점" },
          { key: "protectedTenant", label: "환산보증금 기준 보호대상", type: "select", placeholder: "선택", options: ["해당(보호대상)", "비해당(고액)", "확인 필요"] },
        ],
        considerations: [
          "상가건물임대차보호법은 환산보증금 기준 이하 임차인을 보호합니다.",
          "계약갱신요구권은 최초 임대차 포함 총 10년까지 보장됩니다.",
          "권리금 회수기회 보호 규정(2015년 시행)이 핵심 쟁점입니다.",
          "임대료 인상률은 연 5% 상한 규정이 적용됩니다.",
        ],
        references: [
          { name: "법제처 국가법령정보센터", url: "https://www.law.go.kr" },
          { name: "대한법률구조공단", url: "https://www.klac.or.kr" },
          { name: "대법원 판례정보시스템", url: "https://glaw.scourt.go.kr" },
        ],
      },
      {
        name: "프랜차이즈 분쟁 판단",
        desc: "프랜차이즈 가맹 분쟁 해결 가능성",
        diff: "정밀",
        time: 10,
        docs: ["가맹계약서", "분쟁 내용", "매출 자료"],
        fields: [
          { key: "disputeType", label: "분쟁 유형", type: "select", placeholder: "선택", options: ["허위정보 제공", "영업지역 침해", "부당 해지", "필수품 강제 구매", "인테리어 비용 분쟁", "가맹비 반환"] },
          { key: "franchiseFee", label: "가맹비 총액", type: "number", placeholder: "예: 30000000" },
          { key: "contractPeriod", label: "계약 기간(년)", type: "number", placeholder: "예: 3" },
          { key: "monthlySales", label: "월 평균 매출", type: "number", placeholder: "예: 15000000" },
          { key: "promisedSales", label: "가맹본부 제시 예상 매출", type: "number", placeholder: "예: 25000000" },
          { key: "hasInfoSheet", label: "정보공개서 수령 여부", type: "select", placeholder: "선택", options: ["수령함", "미수령", "허위 기재 의심"] },
          { key: "evidenceLevel", label: "증거 수준", type: "select", placeholder: "선택", options: ["계약서+녹취+문서", "계약서만", "구두 약속만"] },
        ],
        considerations: [
          "가맹사업거래의 공정화에 관한 법률이 가맹점주를 보호합니다.",
          "정보공개서의 허위·과장 기재는 계약 취소 사유가 됩니다.",
          "공정거래위원회 가맹분쟁조정협의회를 통한 조정이 가능합니다.",
          "영업지역 침해(근거리 동일 가맹점 개설)는 손해배상 사유입니다.",
          "부당한 계약 해지 시 손해배상 및 가맹비 반환 청구가 가능합니다.",
        ],
        references: [
          { name: "공정거래위원회 가맹사업정보", url: "https://franchise.ftc.go.kr" },
          { name: "법제처 국가법령정보센터", url: "https://www.law.go.kr" },
          { name: "대한법률구조공단", url: "https://www.klac.or.kr" },
          { name: "대법원 판례정보시스템", url: "https://glaw.scourt.go.kr" },
        ],
      },
      {
        name: "근로기준법 위반 리스크",
        desc: "근로기준법 위반 가능성 및 과태료 시뮬레이션",
        diff: "표준",
        time: 7,
        docs: ["근로계약서", "급여대장", "근무시간 기록"],
        fields: [
          { key: "employeeCount", label: "상시 근로자 수", type: "number", placeholder: "예: 8" },
          { key: "hasContract", label: "근로계약서 작성 여부", type: "select", placeholder: "선택", options: ["전원 작성", "일부 미작성", "전원 미작성"] },
          { key: "weeklyHours", label: "주당 평균 근로시간", type: "number", placeholder: "예: 52" },
          { key: "overtimePay", label: "연장근로 수당 지급", type: "select", placeholder: "선택", options: ["정상 지급", "일부 미지급", "전혀 미지급", "포괄임금제 적용"] },
          { key: "minimumWage", label: "최저임금 준수 여부", type: "select", placeholder: "선택", options: ["준수", "미달 의심", "미달 확인"] },
          { key: "annualLeave", label: "연차 부여/사용 현황", type: "select", placeholder: "선택", options: ["정상 부여", "일부 미부여", "연차 미부여"] },
        ],
        considerations: [
          "5인 이상 사업장은 근로기준법 전면 적용, 5인 미만은 일부 적용입니다.",
          "근로계약서 미교부 시 500만원 이하 벌금에 처해질 수 있습니다.",
          "주 52시간(연장 포함) 위반 시 2년 이하 징역 또는 2천만원 이하 벌금입니다.",
          "최저임금 미달 시 3년 이하 징역 또는 2천만원 이하 벌금입니다.",
          "포괄임금제라도 실제 연장근로가 초과하면 추가 수당 지급 의무가 있습니다.",
        ],
        references: [
          { name: "고용노동부", url: "https://www.moel.go.kr" },
          { name: "법제처 국가법령정보센터", url: "https://www.law.go.kr" },
          { name: "대법원 판례정보시스템", url: "https://glaw.scourt.go.kr" },
        ],
      },
    ],
    corp: [
      {
        name: "공정거래 위반 리스크",
        desc: "공정거래법 위반 가능성 진단",
        diff: "정밀",
        time: 12,
        docs: ["거래 구조", "계약서", "시장 점유율"],
        fields: [
          { key: "violationType", label: "의심 유형", type: "select", placeholder: "선택", options: ["시장지배적 지위 남용", "부당 공동행위(담합)", "불공정거래행위", "기업결합 제한", "재판매가격 유지", "부당 내부거래"] },
          { key: "marketShare", label: "시장 점유율(%)", type: "number", placeholder: "예: 35" },
          { key: "annualRevenue", label: "연매출(억원)", type: "number", placeholder: "예: 500" },
          { key: "competitorCount", label: "주요 경쟁사 수", type: "number", placeholder: "예: 5" },
          { key: "transactionStructure", label: "문제 거래 유형", type: "text", placeholder: "예: 하도급업체 단가 일방 인하" },
          { key: "duration", label: "행위 지속 기간", type: "text", placeholder: "예: 약 2년" },
        ],
        considerations: [
          "시장지배적 사업자(점유율 50% 이상 또는 상위 3사 합산 75% 이상) 판단이 우선입니다.",
          "부당 공동행위(담합) 적발 시 관련 매출의 최대 10% 과징금이 부과됩니다.",
          "자진신고 감면(리니언시) 제도를 활용하면 과징금 면제/감경 가능합니다.",
          "하도급법 위반(단가 인하 강요, 대금 미지급 등)은 별도 규제 대상입니다.",
          "공정거래위원회 조사 시 임의조사·강제조사 구분이 중요합니다.",
        ],
        references: [
          { name: "공정거래위원회", url: "https://www.ftc.go.kr" },
          { name: "법제처 국가법령정보센터", url: "https://www.law.go.kr" },
          { name: "대법원 판례정보시스템", url: "https://glaw.scourt.go.kr" },
        ],
      },
      {
        name: "지식재산권 침해 판단",
        desc: "특허·상표·저작권 침해 가능성 진단",
        diff: "정밀",
        time: 10,
        docs: ["지재권 정보", "침해 의심 내용", "관련 자료"],
        fields: [
          { key: "ipType", label: "지재권 유형", type: "select", placeholder: "선택", options: ["특허권", "실용신안권", "디자인권", "상표권", "저작권", "영업비밀"] },
          { key: "role", label: "당사 입장", type: "select", placeholder: "선택", options: ["권리자(침해당함)", "침해 의심자(피소 위험)"] },
          { key: "registrationStatus", label: "권리 등록 상태", type: "select", placeholder: "선택", options: ["등록 완료", "출원 중", "미등록"] },
          { key: "similarityLevel", label: "유사도 수준", type: "select", placeholder: "선택", options: ["거의 동일", "상당히 유사", "부분 유사", "일부 요소만 유사"] },
          { key: "commercialUse", label: "상업적 이용 여부", type: "select", placeholder: "선택", options: ["대규모 상업적 이용", "소규모 상업적 이용", "비상업적 이용"] },
          { key: "damageEstimate", label: "예상 손해 규모", type: "number", placeholder: "예: 100000000" },
          { key: "priorArt", label: "선행기술/선사용 항변 가능", type: "select", placeholder: "선택", options: ["가능", "불가능", "확인 필요"] },
        ],
        considerations: [
          "특허 침해 판단은 청구항(claim)의 구성요소 대비 분석이 핵심입니다.",
          "상표권 침해는 동일·유사 상품에 대한 혼동 가능성으로 판단합니다.",
          "저작권은 창작 시 자동 발생하며, 등록은 대항력 확보 수단입니다.",
          "손해배상 산정은 실손해, 침해자 이익, 실시료 상당액 중 선택 가능합니다.",
          "가처분(침해금지) 신청으로 긴급 구제를 받을 수 있습니다.",
        ],
        references: [
          { name: "특허정보검색서비스(KIPRIS)", url: "https://www.kipris.or.kr" },
          { name: "법제처 국가법령정보센터", url: "https://www.law.go.kr" },
          { name: "대법원 판례정보시스템", url: "https://glaw.scourt.go.kr" },
          { name: "한국지식재산보호원", url: "https://www.koipa.re.kr" },
        ],
      },
      {
        name: "계약 리스크 분석",
        desc: "계약서 리스크 조항 분석 및 진단",
        diff: "표준",
        time: 7,
        docs: ["계약서 사본", "거래 조건"],
        fields: [
          { key: "contractType", label: "계약 유형", type: "select", placeholder: "선택", options: ["공급 계약", "용역 계약", "라이선스 계약", "합작투자 계약", "M&A 계약", "임대차 계약", "기타"] },
          { key: "contractValue", label: "계약 금액", type: "number", placeholder: "예: 500000000" },
          { key: "contractPeriod", label: "계약 기간", type: "text", placeholder: "예: 2년" },
          { key: "counterpartyType", label: "상대방 유형", type: "select", placeholder: "선택", options: ["대기업", "중소기업", "외국 기업", "공공기관", "개인"] },
          { key: "mainConcern", label: "주요 우려 조항", type: "select", placeholder: "선택", options: ["손해배상 한도", "계약 해지 조건", "위약금", "지재권 귀속", "비밀유지", "경업금지", "준거법/관할"] },
          { key: "hasLegalReview", label: "법률 검토 여부", type: "select", placeholder: "선택", options: ["미검토", "내부 검토 완료", "외부 자문 완료"] },
        ],
        considerations: [
          "계약 해지/해제 조항의 구체성과 불가항력(Force Majeure) 조항을 확인합니다.",
          "손해배상 상한/하한 조항과 면책 범위를 면밀히 검토해야 합니다.",
          "지재권 귀속 조항은 특히 용역/개발 계약에서 핵심 쟁점입니다.",
          "준거법과 분쟁해결 방법(소송 vs 중재)이 명시되어 있는지 확인합니다.",
        ],
        references: [
          { name: "법제처 국가법령정보센터", url: "https://www.law.go.kr" },
          { name: "대한상사중재원", url: "https://www.kcab.or.kr" },
          { name: "대법원 판례정보시스템", url: "https://glaw.scourt.go.kr" },
        ],
      },
      {
        name: "노동쟁의 리스크",
        desc: "노동쟁의 발생 가능성 및 대응 시뮬레이션",
        diff: "정밀",
        time: 10,
        docs: ["노동조합 현황", "근로조건", "분쟁 이력"],
        fields: [
          { key: "employeeCount", label: "전체 직원 수", type: "number", placeholder: "예: 200" },
          { key: "unionStatus", label: "노동조합 현황", type: "select", placeholder: "선택", options: ["기업별 노조 있음", "산별 노조 가입", "복수 노조", "노조 없음", "노조 설립 움직임"] },
          { key: "unionRate", label: "노조 가입률(%)", type: "number", placeholder: "예: 45" },
          { key: "disputeType", label: "주요 쟁점", type: "select", placeholder: "선택", options: ["임금 인상", "구조조정/정리해고", "근로조건 변경", "단체협약 갱신", "부당노동행위", "비정규직 처우"] },
          { key: "priorDispute", label: "과거 쟁의 이력", type: "select", placeholder: "선택", options: ["없음", "1회", "2회 이상", "현재 진행 중"] },
          { key: "negotiationStatus", label: "교섭 상태", type: "select", placeholder: "선택", options: ["교섭 전", "교섭 진행 중", "교섭 결렬", "쟁의 조정 중"] },
          { key: "urgencyLevel", label: "긴급도", type: "select", placeholder: "선택", options: ["예방 차원", "분쟁 초기", "쟁의 임박", "파업 진행 중"] },
        ],
        considerations: [
          "정당한 쟁의행위는 민·형사상 면책이 보장됩니다(노동조합법 제3·4조).",
          "조정 전치주의: 노동위원회 조정 절차를 먼저 거쳐야 합법적 쟁의가 가능합니다.",
          "부당노동행위(노조 활동 방해, 불이익 처분 등)는 2년 이하 징역입니다.",
          "정리해고는 긴박한 경영상의 필요, 해고 회피 노력, 합리적 기준 등 엄격한 요건이 필요합니다.",
          "필수유지업무 제도(공공 부문 등)에 해당하면 전면 파업이 제한됩니다.",
        ],
        references: [
          { name: "중앙노동위원회", url: "https://www.nlrc.go.kr" },
          { name: "고용노동부", url: "https://www.moel.go.kr" },
          { name: "법제처 국가법령정보센터", url: "https://www.law.go.kr" },
          { name: "대법원 판례정보시스템", url: "https://glaw.scourt.go.kr" },
        ],
      },
    ],
  },

  tax: {
    personal: [
      {
        name: "종합소득세 시뮬레이션",
        desc: "종합소득세 예상 세액 계산",
        diff: "표준",
        time: 5,
        docs: ["소득 내역", "공제 항목"],
        fields: [
          { key: "salary", label: "근로소득(연)", type: "number", placeholder: "예: 60000000" },
          { key: "businessIncome", label: "사업소득(연)", type: "number", placeholder: "예: 0" },
          { key: "rentalIncome", label: "임대소득(연)", type: "number", placeholder: "예: 12000000" },
          { key: "otherIncome", label: "기타소득(연)", type: "number", placeholder: "예: 5000000" },
          { key: "dependents", label: "부양가족 수", type: "number", placeholder: "예: 3" },
          { key: "insurancePremium", label: "보험료 공제(연)", type: "number", placeholder: "예: 2000000" },
          { key: "medicalExpense", label: "의료비 지출(연)", type: "number", placeholder: "예: 3000000" },
          { key: "donationAmount", label: "기부금(연)", type: "number", placeholder: "예: 1000000" },
        ],
        considerations: [
          "종합소득세율은 1,400만원 이하 6%에서 10억 초과 45%까지 8단계 누진 구조입니다.",
          "근로소득공제, 인적공제, 특별소득공제 등을 최대한 활용해야 합니다.",
          "분리과세 선택 가능 소득(주택임대소득 2천만원 이하 등)을 확인합니다.",
          "성실신고확인 대상(업종별 매출 기준)에 해당하면 별도 절차가 필요합니다.",
        ],
        references: [
          { name: "국세청 홈택스", url: "https://www.hometax.go.kr" },
          { name: "국세법령정보시스템", url: "https://txsi.hometax.go.kr" },
          { name: "한국세무사회", url: "https://www.kacpta.or.kr" },
        ],
      },
      {
        name: "연말정산 최적화",
        desc: "연말정산 환급액 최적화 시뮬레이션",
        diff: "표준",
        time: 7,
        docs: ["급여명세서", "공제 증빙", "카드 사용 내역"],
        fields: [
          { key: "annualSalary", label: "총 급여액(연)", type: "number", placeholder: "예: 55000000" },
          { key: "creditCard", label: "신용카드 사용액(연)", type: "number", placeholder: "예: 15000000" },
          { key: "debitCard", label: "체크카드/현금영수증(연)", type: "number", placeholder: "예: 8000000" },
          { key: "traditionalMarket", label: "전통시장 사용액(연)", type: "number", placeholder: "예: 1000000" },
          { key: "medicalExpense", label: "의료비 지출(연)", type: "number", placeholder: "예: 2500000" },
          { key: "educationExpense", label: "교육비 지출(연)", type: "number", placeholder: "예: 4000000" },
          { key: "pensionSaving", label: "연금저축 납입액(연)", type: "number", placeholder: "예: 4000000" },
          { key: "housingLoanInterest", label: "주택 대출 이자(연)", type: "number", placeholder: "예: 6000000" },
        ],
        considerations: [
          "카드 소득공제는 총급여 25% 초과분부터 적용(체크카드 30%, 신용카드 15%)됩니다.",
          "연금저축+IRP 합산 세액공제 한도는 연 900만원(총급여 5,500만원 이하 15%)입니다.",
          "의료비는 총급여 3% 초과분부터 공제 가능합니다.",
          "주택자금 공제(장기주택저당차입금 이자 상환액)는 무주택 또는 1주택자만 가능합니다.",
          "월세 세액공제(총급여 7천만원 이하, 최대 17%)도 놓치지 않아야 합니다.",
        ],
        references: [
          { name: "국세청 홈택스 연말정산", url: "https://www.hometax.go.kr" },
          { name: "국세법령정보시스템", url: "https://txsi.hometax.go.kr" },
          { name: "한국세무사회", url: "https://www.kacpta.or.kr" },
        ],
      },
      {
        name: "증여세 시뮬레이션",
        desc: "증여 시 세금 계산 시뮬레이션",
        diff: "표준",
        time: 5,
        docs: ["증여 재산", "증여자/수증자 관계", "사전 증여 이력"],
        fields: [
          { key: "giftAmount", label: "증여 재산 가액", type: "number", placeholder: "예: 200000000" },
          { key: "giftType", label: "증여 재산 유형", type: "select", placeholder: "선택", options: ["현금", "부동산", "주식(상장)", "주식(비상장)", "기타 자산"] },
          { key: "relationship", label: "증여자와의 관계", type: "select", placeholder: "선택", options: ["배우자", "직계존속(부모)", "직계비속(자녀)", "직계비속(미성년)", "기타 친족", "타인"] },
          { key: "priorGift10yr", label: "10년 내 사전증여 합계", type: "number", placeholder: "예: 50000000" },
          { key: "recipientAge", label: "수증자 연령", type: "number", placeholder: "예: 35" },
          { key: "purpose", label: "증여 목적", type: "select", placeholder: "선택", options: ["주택 구입 자금", "사업 자금", "교육비", "생활비", "결혼 자금", "기타"] },
        ],
        considerations: [
          "증여세 면제한도: 배우자 6억, 직계존속 5천만원(미성년 2천만원), 기타 친족 1천만원입니다.",
          "10년 합산 과세: 동일인으로부터 10년간 증여받은 금액을 합산합니다.",
          "부동산 증여 시 시가(감정가 또는 공시가) 기준 평가가 중요합니다.",
          "부담부증여(채무 인수 포함)는 증여세+양도세가 동시에 발생할 수 있습니다.",
          "창업자금 증여(50억 한도, 10% 세율)와 혼인·출산 증여(1억 추가공제) 특례도 검토합니다.",
        ],
        references: [
          { name: "국세청 홈택스", url: "https://www.hometax.go.kr" },
          { name: "국세법령정보시스템", url: "https://txsi.hometax.go.kr" },
          { name: "기획재정부 세법해석례", url: "https://www.moef.go.kr" },
        ],
      },
      {
        name: "상속세 시뮬레이션",
        desc: "상속재산 규모별 상속세 계산",
        diff: "정밀",
        time: 10,
        docs: ["상속재산 목록", "상속인 정보", "채무 내역"],
        fields: [
          { key: "totalEstate", label: "상속재산 총액", type: "number", placeholder: "예: 2000000000" },
          { key: "realEstateValue", label: "부동산 가액", type: "number", placeholder: "예: 1200000000" },
          { key: "financialAsset", label: "금융재산", type: "number", placeholder: "예: 500000000" },
          { key: "liabilities", label: "채무 총액", type: "number", placeholder: "예: 200000000" },
          { key: "spouseInherit", label: "배우자 상속 여부", type: "select", placeholder: "선택", options: ["있음", "없음"] },
          { key: "heirCount", label: "상속인 수", type: "number", placeholder: "예: 3" },
          { key: "priorGift", label: "10년 내 사전증여 합계", type: "number", placeholder: "예: 200000000" },
          { key: "funeralExpense", label: "장례비용", type: "number", placeholder: "예: 10000000" },
        ],
        considerations: [
          "기초공제(2억) + 인적공제 vs 일괄공제(5억) 중 유리한 것을 선택합니다.",
          "배우자 상속공제는 법정상속분 내에서 최소 5억~최대 30억까지 공제됩니다.",
          "금융재산 공제(순금융재산의 20%, 최대 2억)를 활용합니다.",
          "상속세율은 1억 이하 10%~30억 초과 50%까지 5단계입니다.",
          "가업상속공제(최대 600억), 영농상속공제(최대 30억) 특례도 해당 여부를 확인합니다.",
        ],
        references: [
          { name: "국세청 홈택스", url: "https://www.hometax.go.kr" },
          { name: "국세법령정보시스템", url: "https://txsi.hometax.go.kr" },
          { name: "기획재정부 세법해석례", url: "https://www.moef.go.kr" },
          { name: "한국세무사회", url: "https://www.kacpta.or.kr" },
        ],
      },
      {
        name: "양도소득세 시뮬레이션",
        desc: "양도소득세 예상 세액 계산",
        diff: "표준",
        time: 5,
        docs: ["취득가", "양도가", "보유기간"],
        fields: [
          { key: "assetType", label: "양도 자산 유형", type: "select", placeholder: "선택", options: ["주택", "토지", "상가/오피스", "분양권", "조합원입주권", "비상장주식"] },
          { key: "acquisitionPrice", label: "취득가액", type: "number", placeholder: "예: 300000000" },
          { key: "salePrice", label: "양도가액", type: "number", placeholder: "예: 500000000" },
          { key: "holdingPeriod", label: "보유 기간(년)", type: "number", placeholder: "예: 5" },
          { key: "residencePeriod", label: "거주 기간(년)", type: "number", placeholder: "예: 3" },
          { key: "houseCount", label: "보유 주택 수", type: "select", placeholder: "선택", options: ["1주택", "2주택", "3주택 이상"] },
          { key: "improvementCost", label: "필요경비(인테리어 등)", type: "number", placeholder: "예: 20000000" },
        ],
        considerations: [
          "1세대 1주택(2년 보유, 조정지역 2년 거주)은 12억까지 비과세입니다.",
          "다주택자 중과세율(기본세율 + 20~30%p)은 현재 한시 유예 여부를 확인해야 합니다.",
          "장기보유특별공제(최대 80%)는 보유·거주 기간에 따라 달라집니다.",
          "필요경비(취득세, 인테리어, 중개수수료 등)를 빠짐없이 반영해야 합니다.",
          "양도 시기(잔금일 vs 등기일)에 따라 세액이 달라질 수 있습니다.",
        ],
        references: [
          { name: "국세청 홈택스", url: "https://www.hometax.go.kr" },
          { name: "국세법령정보시스템", url: "https://txsi.hometax.go.kr" },
          { name: "한국세무사회", url: "https://www.kacpta.or.kr" },
        ],
      },
      {
        name: "금융소득 종합과세 시뮬레이션",
        desc: "금융소득 종합과세 해당 여부 및 세액 계산",
        diff: "표준",
        time: 5,
        docs: ["이자소득", "배당소득", "기타 소득"],
        fields: [
          { key: "interestIncome", label: "이자소득(연)", type: "number", placeholder: "예: 15000000" },
          { key: "dividendIncome", label: "배당소득(연)", type: "number", placeholder: "예: 10000000" },
          { key: "otherIncome", label: "근로/사업소득(연)", type: "number", placeholder: "예: 50000000" },
          { key: "taxExemptFinancial", label: "비과세 금융소득", type: "number", placeholder: "예: 2000000" },
          { key: "separateTaxFinancial", label: "분리과세 금융소득", type: "number", placeholder: "예: 3000000" },
          { key: "grossUpApplicable", label: "Gross-up 대상 배당", type: "select", placeholder: "선택", options: ["있음", "없음", "확인 필요"] },
        ],
        considerations: [
          "금융소득(이자+배당) 합계 2,000만원 초과 시 종합과세 대상입니다.",
          "종합과세 시 산출세액은 '분리과세 비교세액'과 비교하여 큰 금액을 적용합니다.",
          "Gross-up(배당세액공제)은 법인세 이중과세 조정을 위한 제도입니다.",
          "비과세(ISA 등)·분리과세 상품을 활용하여 2,000만원 기준을 관리하는 것이 핵심입니다.",
        ],
        references: [
          { name: "국세청 홈택스", url: "https://www.hometax.go.kr" },
          { name: "국세법령정보시스템", url: "https://txsi.hometax.go.kr" },
          { name: "기획재정부 세법해석례", url: "https://www.moef.go.kr" },
        ],
      },
      {
        name: "해외주식 양도세 시뮬레이션",
        desc: "해외주식 양도소득세 예상 세액 계산",
        diff: "간편",
        time: 3,
        docs: ["매수가", "매도가", "거래 내역"],
        fields: [
          { key: "totalProceeds", label: "총 매도 금액(원화)", type: "number", placeholder: "예: 100000000" },
          { key: "totalCost", label: "총 매수 금액(원화)", type: "number", placeholder: "예: 70000000" },
          { key: "fees", label: "수수료/제비용 합계", type: "number", placeholder: "예: 500000" },
          { key: "exchangeMethod", label: "환율 적용 방식", type: "select", placeholder: "선택", options: ["매도 시점 환율", "평균 환율", "증권사 자동 계산"] },
          { key: "otherCapitalGain", label: "기타 양도소득(국내 포함)", type: "number", placeholder: "예: 0" },
          { key: "lossCarryForward", label: "이월 결손금", type: "number", placeholder: "예: 0" },
        ],
        considerations: [
          "해외주식 양도소득은 연간 250만원 기본공제 후 22%(지방세 포함) 과세입니다.",
          "같은 해에 발생한 해외주식 손익은 통산(합산) 가능합니다.",
          "국내 상장주식 대주주 양도차익과 해외주식 양도차익은 별도 계산합니다.",
          "매년 5월에 확정 신고·납부해야 하며, 미신고 시 가산세가 부과됩니다.",
        ],
        references: [
          { name: "국세청 홈택스", url: "https://www.hometax.go.kr" },
          { name: "국세법령정보시스템", url: "https://txsi.hometax.go.kr" },
          { name: "한국세무사회", url: "https://www.kacpta.or.kr" },
        ],
      },
    ],
    sole: [
      {
        name: "부가세 신고 시뮬레이션",
        desc: "부가가치세 예상 납부액 계산",
        diff: "표준",
        time: 5,
        docs: ["매출/매입 내역", "세금계산서"],
        fields: [
          { key: "salesAmount", label: "과세 매출(분기)", type: "number", placeholder: "예: 50000000" },
          { key: "zeroRateSales", label: "영세율 매출", type: "number", placeholder: "예: 0" },
          { key: "exemptSales", label: "면세 매출", type: "number", placeholder: "예: 5000000" },
          { key: "purchaseAmount", label: "매입액(세금계산서 기준)", type: "number", placeholder: "예: 30000000" },
          { key: "creditCardPurchase", label: "신용카드 매입(세금계산서 외)", type: "number", placeholder: "예: 5000000" },
          { key: "fixedAssetPurchase", label: "고정자산 매입", type: "number", placeholder: "예: 10000000" },
          { key: "taxationType", label: "과세 유형", type: "select", placeholder: "선택", options: ["일반과세자", "간이과세자"] },
        ],
        considerations: [
          "부가세 = 매출세액(매출의 10%) - 매입세액(적격 증빙 매입의 10%)입니다.",
          "세금계산서, 신용카드 매출전표, 현금영수증이 적격 증빙입니다.",
          "간이과세자는 업종별 부가가치율을 적용하여 세액을 계산합니다.",
          "고정자산 매입(설비, 차량 등)의 매입세액은 전액 공제 가능합니다.",
          "면세사업 겸업 시 공통매입세액 안분계산이 필요합니다.",
        ],
        references: [
          { name: "국세청 홈택스", url: "https://www.hometax.go.kr" },
          { name: "국세법령정보시스템", url: "https://txsi.hometax.go.kr" },
          { name: "한국세무사회", url: "https://www.kacpta.or.kr" },
        ],
      },
      {
        name: "종합소득세 절세",
        desc: "개인사업자 종합소득세 절세 방안",
        diff: "표준",
        time: 7,
        docs: ["사업소득 내역", "경비 내역", "공제 항목"],
        fields: [
          { key: "annualRevenue", label: "연 매출", type: "number", placeholder: "예: 150000000" },
          { key: "annualExpense", label: "연 경비(원재료+인건비+임차료 등)", type: "number", placeholder: "예: 100000000" },
          { key: "businessType", label: "업종", type: "text", placeholder: "예: 음식점업" },
          { key: "expenseMethod", label: "경비 처리 방식", type: "select", placeholder: "선택", options: ["장부 기장(복식부기)", "장부 기장(간편장부)", "추계(단순경비율)", "추계(기준경비율)"] },
          { key: "pensionSaving", label: "연금저축 납입(연)", type: "number", placeholder: "예: 4000000" },
          { key: "noraePension", label: "노란우산공제 납입(연)", type: "number", placeholder: "예: 3000000" },
          { key: "dependents", label: "부양가족 수", type: "number", placeholder: "예: 2" },
        ],
        considerations: [
          "장부 기장이 추계보다 유리한 경우가 대부분이며, 기장세액공제(20%)도 받을 수 있습니다.",
          "노란우산공제는 소득공제(최대 500만원) + 압류 방지 혜택이 있습니다.",
          "성실신고확인 대상(업종별 매출 기준)이면 의료비·교육비 공제가 추가됩니다.",
          "법인 전환 시 절세 효과가 있는지도 비교 분석이 필요합니다.",
          "차량, 접대비, 기부금 등 한도가 있는 경비 항목을 정확히 관리해야 합니다.",
        ],
        references: [
          { name: "국세청 홈택스", url: "https://www.hometax.go.kr" },
          { name: "국세법령정보시스템", url: "https://txsi.hometax.go.kr" },
          { name: "한국세무사회", url: "https://www.kacpta.or.kr" },
          { name: "중소벤처기업부 노란우산", url: "https://www.8899.or.kr" },
        ],
      },
      {
        name: "간이과세 전환 적격",
        desc: "간이과세자 전환 적격 여부 진단",
        diff: "간편",
        time: 3,
        docs: ["매출 내역", "업종 정보"],
        fields: [
          { key: "annualSales", label: "직전연도 매출", type: "number", placeholder: "예: 70000000" },
          { key: "businessType", label: "업종", type: "text", placeholder: "예: 소매업" },
          { key: "location", label: "사업장 소재지", type: "text", placeholder: "예: 서울시 강남구" },
          { key: "isExcluded", label: "간이과세 배제 업종 여부", type: "select", placeholder: "선택", options: ["해당없음", "부동산임대업", "유흥업", "전문직", "확인 필요"] },
          { key: "hasIssueInvoice", label: "세금계산서 발급 필요", type: "select", placeholder: "선택", options: ["거래처가 요구함", "필요 없음", "일부 필요"] },
        ],
        considerations: [
          "연 매출 1억 400만원(2024년 기준) 미만이면 간이과세 적용 가능합니다.",
          "간이과세자는 업종별 부가가치율(5~40%)로 부가세를 계산하여 세 부담이 낮습니다.",
          "매출 4,800만원 미만이면 부가세 납부 면제입니다.",
          "단, 간이과세자는 세금계산서 발급이 제한되어 B2B 거래에 불리합니다.",
          "부동산임대업, 과세유흥장소 등 일부 업종은 간이과세 배제됩니다.",
        ],
        references: [
          { name: "국세청 홈택스", url: "https://www.hometax.go.kr" },
          { name: "국세법령정보시스템", url: "https://txsi.hometax.go.kr" },
          { name: "한국세무사회", url: "https://www.kacpta.or.kr" },
        ],
      },
      {
        name: "세무조사 리스크 진단",
        desc: "세무조사 대상 선정 가능성 진단",
        diff: "정밀",
        time: 10,
        docs: ["매출 내역", "신고 이력", "업종 정보"],
        fields: [
          { key: "annualSales", label: "연 매출", type: "number", placeholder: "예: 200000000" },
          { key: "reportedIncome", label: "신고 소득", type: "number", placeholder: "예: 30000000" },
          { key: "businessType", label: "업종", type: "text", placeholder: "예: 음식점업" },
          { key: "businessYears", label: "사업 연수", type: "number", placeholder: "예: 7" },
          { key: "cardSalesRatio", label: "카드 매출 비율(%)", type: "number", placeholder: "예: 60" },
          { key: "priorAudit", label: "과거 세무조사 이력", type: "select", placeholder: "선택", options: ["없음", "있음(추징 없음)", "있음(추징 있음)"] },
          { key: "riskFactor", label: "우려 사항", type: "select", placeholder: "선택", options: ["현금 매출 누락 의심", "가공경비 사용", "매출 급변동", "동업종 대비 소득률 낮음", "특별한 우려 없음"] },
        ],
        considerations: [
          "국세청 전산 분석(AIS)으로 동업종 대비 소득률이 현저히 낮으면 선정됩니다.",
          "카드·현금영수증 매출 비율이 낮으면 현금 매출 누락 의심을 받습니다.",
          "무작위 추출(정기조사)과 혐의 기반(비정기조사)이 있습니다.",
          "세무조사 주기는 일반적으로 5~7년이지만, 리스크 요인에 따라 단축됩니다.",
          "조사 대응 시 장부·증빙의 정리 상태가 결과에 큰 영향을 미칩니다.",
        ],
        references: [
          { name: "국세청 홈택스", url: "https://www.hometax.go.kr" },
          { name: "국세법령정보시스템", url: "https://txsi.hometax.go.kr" },
          { name: "한국세무사회", url: "https://www.kacpta.or.kr" },
          { name: "기획재정부 세법해석례", url: "https://www.moef.go.kr" },
        ],
      },
    ],
    corp: [
      {
        name: "법인세 시뮬레이션",
        desc: "법인세 예상 세액 계산",
        diff: "표준",
        time: 7,
        docs: ["재무제표", "세무 조정 내역"],
        fields: [
          { key: "revenue", label: "매출(연)", type: "number", placeholder: "예: 5000000000" },
          { key: "accountingProfit", label: "회계상 당기순이익", type: "number", placeholder: "예: 500000000" },
          { key: "taxAdjustPlus", label: "세무조정 가산(익금산입)", type: "number", placeholder: "예: 50000000" },
          { key: "taxAdjustMinus", label: "세무조정 차감(손금산입)", type: "number", placeholder: "예: 30000000" },
          { key: "taxCredit", label: "세액공제 예상(합계)", type: "number", placeholder: "예: 20000000" },
          { key: "companySize", label: "기업 규모", type: "select", placeholder: "선택", options: ["중소기업", "중견기업", "대기업"] },
          { key: "priorLoss", label: "이월결손금", type: "number", placeholder: "예: 100000000" },
        ],
        considerations: [
          "법인세율: 2억 이하 9%, 2~200억 19%, 200~3,000억 21%, 3,000억 초과 24%입니다.",
          "이월결손금 공제는 중소기업 100%, 대기업 80% 한도입니다.",
          "접대비, 기부금, 감가상각비 등 손금 한도 항목을 정확히 반영해야 합니다.",
          "중소기업 특별세액감면(5~30%)은 업종·지역에 따라 달라집니다.",
          "법인세 중간예납(상반기 기준) 납부도 고려해야 합니다.",
        ],
        references: [
          { name: "국세청 홈택스", url: "https://www.hometax.go.kr" },
          { name: "국세법령정보시스템", url: "https://txsi.hometax.go.kr" },
          { name: "한국세무사회", url: "https://www.kacpta.or.kr" },
          { name: "기획재정부 세법해석례", url: "https://www.moef.go.kr" },
        ],
      },
      {
        name: "이전가격 리스크",
        desc: "이전가격 세무 리스크 진단",
        diff: "정밀",
        time: 15,
        docs: ["관계사 거래 내역", "이전가격 보고서"],
        fields: [
          { key: "relatedPartyTx", label: "관계사 거래 규모(연)", type: "number", placeholder: "예: 10000000000" },
          { key: "txType", label: "주요 거래 유형", type: "select", placeholder: "선택", options: ["유형 재화 거래", "용역 거래", "무형자산 거래(로열티)", "자금 대여/차입", "혼합 거래"] },
          { key: "counterpartyCountry", label: "상대방 소재국", type: "text", placeholder: "예: 미국, 싱가포르" },
          { key: "hasTPReport", label: "이전가격 보고서 구비", type: "select", placeholder: "선택", options: ["있음(최신)", "있음(오래됨)", "없음"] },
          { key: "pricingMethod", label: "적용 이전가격 방법", type: "select", placeholder: "선택", options: ["비교가능 제3자 가격법", "재판매가격법", "원가가산법", "거래순이익률법", "이익분할법", "미적용/모름"] },
          { key: "profitMargin", label: "관련 거래 영업이익률(%)", type: "number", placeholder: "예: 5" },
        ],
        considerations: [
          "관계사 간 거래가 정상가격(arm's length price)과 일치하는지가 핵심입니다.",
          "이전가격 보고서(TP Documentation)는 세무조사 시 반드시 제출해야 합니다.",
          "BEPS(세원잠식 방지) 프로젝트에 따라 국가별 보고서(CbCR) 제출 의무가 있습니다.",
          "상호합의절차(MAP)를 통해 이중과세를 해결할 수 있습니다.",
          "이전가격 과세 시 추징세액 + 가산세(과소신고·납부불성실)가 부과됩니다.",
        ],
        references: [
          { name: "국세청 홈택스", url: "https://www.hometax.go.kr" },
          { name: "국세법령정보시스템", url: "https://txsi.hometax.go.kr" },
          { name: "기획재정부 세법해석례", url: "https://www.moef.go.kr" },
          { name: "OECD 이전가격 가이드라인", url: "https://www.oecd.org/tax/transfer-pricing" },
        ],
      },
      {
        name: "세무조사 대비 진단",
        desc: "세무조사 대비 취약점 진단",
        diff: "정밀",
        time: 15,
        docs: ["재무제표 3개년", "세무 조정 내역", "주요 거래 내역"],
        fields: [
          { key: "annualRevenue", label: "연 매출(최근)", type: "number", placeholder: "예: 10000000000" },
          { key: "revenueGrowth", label: "매출 증가율(%)", type: "number", placeholder: "예: 15" },
          { key: "effectiveTaxRate", label: "실효세율(%)", type: "number", placeholder: "예: 18" },
          { key: "relatedPartyTx", label: "특수관계자 거래 비율(%)", type: "number", placeholder: "예: 30" },
          { key: "lastAuditYear", label: "최근 세무조사 연도", type: "text", placeholder: "예: 2020년 (없으면 '없음')" },
          { key: "majorRisk", label: "주요 우려 사항", type: "select", placeholder: "선택", options: ["특수관계자 거래", "해외 거래", "대규모 자산 거래", "비용 처리 적정성", "인건비 관련", "특별한 우려 없음"] },
          { key: "documentLevel", label: "증빙 관리 수준", type: "select", placeholder: "선택", options: ["체계적 관리", "보통", "미흡"] },
        ],
        considerations: [
          "정기 세무조사 주기(대기업 4~5년, 중소기업 무작위)를 파악해야 합니다.",
          "동업종 평균 대비 실효세율이 현저히 낮으면 조사 선정 확률이 높아집니다.",
          "특수관계자 거래, 해외 거래, 대규모 자산 양도는 집중 점검 대상입니다.",
          "조사 유형(정기/비정기/특별)에 따라 대응 전략이 달라집니다.",
          "사전 자체 점검(모의 세무조사)으로 리스크를 사전에 발견·보정할 수 있습니다.",
        ],
        references: [
          { name: "국세청 홈택스", url: "https://www.hometax.go.kr" },
          { name: "국세법령정보시스템", url: "https://txsi.hometax.go.kr" },
          { name: "한국세무사회", url: "https://www.kacpta.or.kr" },
          { name: "기획재정부 세법해석례", url: "https://www.moef.go.kr" },
        ],
      },
      {
        name: "R&D 세액공제 적격",
        desc: "연구개발비 세액공제 적격 여부 진단",
        diff: "표준",
        time: 7,
        docs: ["R&D 과제 내역", "인력 현황", "비용 내역"],
        fields: [
          { key: "rdExpense", label: "R&D 비용(연)", type: "number", placeholder: "예: 500000000" },
          { key: "rdPersonnel", label: "R&D 전담 인력 수", type: "number", placeholder: "예: 10" },
          { key: "hasRdCenter", label: "기업부설연구소/전담부서", type: "select", placeholder: "선택", options: ["기업부설연구소 인정", "연구개발전담부서 인정", "미인정", "신청 예정"] },
          { key: "rdType", label: "R&D 유형", type: "select", placeholder: "선택", options: ["신성장·원천기술", "일반 R&D", "국가전략기술", "혼합"] },
          { key: "companySize", label: "기업 규모", type: "select", placeholder: "선택", options: ["중소기업", "중견기업", "대기업"] },
          { key: "priorYearRd", label: "직전 4년 평균 R&D 비용", type: "number", placeholder: "예: 350000000" },
          { key: "outsourcingRatio", label: "외부 위탁 비율(%)", type: "number", placeholder: "예: 20" },
        ],
        considerations: [
          "중소기업은 당기 R&D 비용의 25% 세액공제(증가분 방식도 선택 가능)입니다.",
          "신성장·원천기술은 중소 30~40%, 중견 20~30%, 대 20~30% 공제됩니다.",
          "국가전략기술 R&D는 추가 우대세율(중소 40~50%, 대 30~40%)이 적용됩니다.",
          "한국산업기술진흥협회(KOITA)의 연구소/전담부서 인정이 필수입니다.",
          "R&D 비용 적격성(인건비, 재료비, 위탁연구비 등) 구분이 중요합니다.",
        ],
        references: [
          { name: "국세청 홈택스", url: "https://www.hometax.go.kr" },
          { name: "국세법령정보시스템", url: "https://txsi.hometax.go.kr" },
          { name: "한국산업기술진흥협회(KOITA)", url: "https://www.koita.or.kr" },
          { name: "기획재정부 세법해석례", url: "https://www.moef.go.kr" },
        ],
      },
    ],
  },
};
